version: '1'
services:

  apache:
    build:
      context: ./Apache24
      dockerfile: Dockerfile
    container_name: apache-container
    ports:
      - "80:80"
    networks:
      - service-network

  connect4:
    build:
      context: ./connect4
      dockerfile: Dockerfile
    container_name: connect4-container
    ports:
      - 3000:3000
    networks:
      - service-network

  voting:
    build:
      context: ./voting
      dockerfile: Dockerfile
    container_name: voting-container
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - service-network

  mongodb:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - ./database/data/db:/data/db
    networks:
      - service-network

volumes:
  mongodb-data:


networks:
  service-network:
