version: '1'
services:

  apache:
    build:
      context: ./Apache24
      dockerfile: Dockerfile
    container_name: voter-apache-container
    ports:
      - "80:80"
    networks:
      - voter-network

  mongodb:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: voter-mongo-container
    ports:
      - "27017:27017"
    volumes:
      - ./database/data/db:/data/db
    networks:
      - voter-network

  nodejs-app:
    build:
      context: ./voting
      dockerfile: Dockerfile
    container_name: voter-node-container
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - voter-network

volumes:
  mongodb-data:


networks:
  voter-network:
