/* X86 Gadgets Table - ROPgadget generator */

#include "ropgadget.h"

t_asm tab_x8632[] = 
{
	{0, 0, "pop %eax ; pop %eax ; pop %eax ; ret", "pop eax ; pop eax ; pop eax ; ret", "\x58\x58\x58\xc3", 4},
	{0, 0, "pop %eax ; pop %eax ; pop %ebx ; ret", "pop eax ; pop eax ; pop ebx ; ret", "\x58\x58\x5b\xc3", 4},
	{0, 0, "pop %eax ; pop %eax ; pop %ecx ; ret", "pop eax ; pop eax ; pop ecx ; ret", "\x58\x58\x59\xc3", 4},
	{0, 0, "pop %eax ; pop %eax ; pop %edx ; ret", "pop eax ; pop eax ; pop edx ; ret", "\x58\x58\x5a\xc3", 4},
	{0, 0, "pop %eax ; pop %eax ; pop %edi ; ret", "pop eax ; pop eax ; pop edi ; ret", "\x58\x58\x5f\xc3", 4},
	{0, 0, "pop %eax ; pop %eax ; pop %esi ; ret", "pop eax ; pop eax ; pop esi ; ret", "\x58\x58\x5e\xc3", 4},
	{0, 0, "pop %eax ; pop %eax ; pop %ebp ; ret", "pop eax ; pop eax ; pop ebp ; ret", "\x58\x58\x5d\xc3", 4},
	{0, 0, "pop %eax ; pop %eax ; pop %esp ; ret", "pop eax ; pop eax ; pop esp ; ret", "\x58\x58\x5c\xc3", 4},
	{0, 0, "pop %eax ; pop %ebx ; pop %eax ; ret", "pop eax ; pop ebx ; pop eax ; ret", "\x58\x5b\x58\xc3", 4},
	{0, 0, "pop %eax ; pop %ebx ; pop %ebx ; ret", "pop eax ; pop ebx ; pop ebx ; ret", "\x58\x5b\x5b\xc3", 4},
	{0, 0, "pop %eax ; pop %ebx ; pop %ecx ; ret", "pop eax ; pop ebx ; pop ecx ; ret", "\x58\x5b\x59\xc3", 4},
	{0, 0, "pop %eax ; pop %ebx ; pop %edx ; ret", "pop eax ; pop ebx ; pop edx ; ret", "\x58\x5b\x5a\xc3", 4},
	{0, 0, "pop %eax ; pop %ebx ; pop %edi ; ret", "pop eax ; pop ebx ; pop edi ; ret", "\x58\x5b\x5f\xc3", 4},
	{0, 0, "pop %eax ; pop %ebx ; pop %esi ; ret", "pop eax ; pop ebx ; pop esi ; ret", "\x58\x5b\x5e\xc3", 4},
	{0, 0, "pop %eax ; pop %ebx ; pop %ebp ; ret", "pop eax ; pop ebx ; pop ebp ; ret", "\x58\x5b\x5d\xc3", 4},
	{0, 0, "pop %eax ; pop %ebx ; pop %esp ; ret", "pop eax ; pop ebx ; pop esp ; ret", "\x58\x5b\x5c\xc3", 4},
	{0, 0, "pop %eax ; pop %ecx ; pop %eax ; ret", "pop eax ; pop ecx ; pop eax ; ret", "\x58\x59\x58\xc3", 4},
	{0, 0, "pop %eax ; pop %ecx ; pop %ebx ; ret", "pop eax ; pop ecx ; pop ebx ; ret", "\x58\x59\x5b\xc3", 4},
	{0, 0, "pop %eax ; pop %ecx ; pop %ecx ; ret", "pop eax ; pop ecx ; pop ecx ; ret", "\x58\x59\x59\xc3", 4},
	{0, 0, "pop %eax ; pop %ecx ; pop %edx ; ret", "pop eax ; pop ecx ; pop edx ; ret", "\x58\x59\x5a\xc3", 4},
	{0, 0, "pop %eax ; pop %ecx ; pop %edi ; ret", "pop eax ; pop ecx ; pop edi ; ret", "\x58\x59\x5f\xc3", 4},
	{0, 0, "pop %eax ; pop %ecx ; pop %esi ; ret", "pop eax ; pop ecx ; pop esi ; ret", "\x58\x59\x5e\xc3", 4},
	{0, 0, "pop %eax ; pop %ecx ; pop %ebp ; ret", "pop eax ; pop ecx ; pop ebp ; ret", "\x58\x59\x5d\xc3", 4},
	{0, 0, "pop %eax ; pop %ecx ; pop %esp ; ret", "pop eax ; pop ecx ; pop esp ; ret", "\x58\x59\x5c\xc3", 4},
	{0, 0, "pop %eax ; pop %edx ; pop %eax ; ret", "pop eax ; pop edx ; pop eax ; ret", "\x58\x5a\x58\xc3", 4},
	{0, 0, "pop %eax ; pop %edx ; pop %ebx ; ret", "pop eax ; pop edx ; pop ebx ; ret", "\x58\x5a\x5b\xc3", 4},
	{0, 0, "pop %eax ; pop %edx ; pop %ecx ; ret", "pop eax ; pop edx ; pop ecx ; ret", "\x58\x5a\x59\xc3", 4},
	{0, 0, "pop %eax ; pop %edx ; pop %edx ; ret", "pop eax ; pop edx ; pop edx ; ret", "\x58\x5a\x5a\xc3", 4},
	{0, 0, "pop %eax ; pop %edx ; pop %edi ; ret", "pop eax ; pop edx ; pop edi ; ret", "\x58\x5a\x5f\xc3", 4},
	{0, 0, "pop %eax ; pop %edx ; pop %esi ; ret", "pop eax ; pop edx ; pop esi ; ret", "\x58\x5a\x5e\xc3", 4},
	{0, 0, "pop %eax ; pop %edx ; pop %ebp ; ret", "pop eax ; pop edx ; pop ebp ; ret", "\x58\x5a\x5d\xc3", 4},
	{0, 0, "pop %eax ; pop %edx ; pop %esp ; ret", "pop eax ; pop edx ; pop esp ; ret", "\x58\x5a\x5c\xc3", 4},
	{0, 0, "pop %eax ; pop %edi ; pop %eax ; ret", "pop eax ; pop edi ; pop eax ; ret", "\x58\x5f\x58\xc3", 4},
	{0, 0, "pop %eax ; pop %edi ; pop %ebx ; ret", "pop eax ; pop edi ; pop ebx ; ret", "\x58\x5f\x5b\xc3", 4},
	{0, 0, "pop %eax ; pop %edi ; pop %ecx ; ret", "pop eax ; pop edi ; pop ecx ; ret", "\x58\x5f\x59\xc3", 4},
	{0, 0, "pop %eax ; pop %edi ; pop %edx ; ret", "pop eax ; pop edi ; pop edx ; ret", "\x58\x5f\x5a\xc3", 4},
	{0, 0, "pop %eax ; pop %edi ; pop %edi ; ret", "pop eax ; pop edi ; pop edi ; ret", "\x58\x5f\x5f\xc3", 4},
	{0, 0, "pop %eax ; pop %edi ; pop %esi ; ret", "pop eax ; pop edi ; pop esi ; ret", "\x58\x5f\x5e\xc3", 4},
	{0, 0, "pop %eax ; pop %edi ; pop %ebp ; ret", "pop eax ; pop edi ; pop ebp ; ret", "\x58\x5f\x5d\xc3", 4},
	{0, 0, "pop %eax ; pop %edi ; pop %esp ; ret", "pop eax ; pop edi ; pop esp ; ret", "\x58\x5f\x5c\xc3", 4},
	{0, 0, "pop %eax ; pop %esi ; pop %eax ; ret", "pop eax ; pop esi ; pop eax ; ret", "\x58\x5e\x58\xc3", 4},
	{0, 0, "pop %eax ; pop %esi ; pop %ebx ; ret", "pop eax ; pop esi ; pop ebx ; ret", "\x58\x5e\x5b\xc3", 4},
	{0, 0, "pop %eax ; pop %esi ; pop %ecx ; ret", "pop eax ; pop esi ; pop ecx ; ret", "\x58\x5e\x59\xc3", 4},
	{0, 0, "pop %eax ; pop %esi ; pop %edx ; ret", "pop eax ; pop esi ; pop edx ; ret", "\x58\x5e\x5a\xc3", 4},
	{0, 0, "pop %eax ; pop %esi ; pop %edi ; ret", "pop eax ; pop esi ; pop edi ; ret", "\x58\x5e\x5f\xc3", 4},
	{0, 0, "pop %eax ; pop %esi ; pop %esi ; ret", "pop eax ; pop esi ; pop esi ; ret", "\x58\x5e\x5e\xc3", 4},
	{0, 0, "pop %eax ; pop %esi ; pop %ebp ; ret", "pop eax ; pop esi ; pop ebp ; ret", "\x58\x5e\x5d\xc3", 4},
	{0, 0, "pop %eax ; pop %esi ; pop %esp ; ret", "pop eax ; pop esi ; pop esp ; ret", "\x58\x5e\x5c\xc3", 4},
	{0, 0, "pop %eax ; pop %ebp ; pop %eax ; ret", "pop eax ; pop ebp ; pop eax ; ret", "\x58\x5d\x58\xc3", 4},
	{0, 0, "pop %eax ; pop %ebp ; pop %ebx ; ret", "pop eax ; pop ebp ; pop ebx ; ret", "\x58\x5d\x5b\xc3", 4},
	{0, 0, "pop %eax ; pop %ebp ; pop %ecx ; ret", "pop eax ; pop ebp ; pop ecx ; ret", "\x58\x5d\x59\xc3", 4},
	{0, 0, "pop %eax ; pop %ebp ; pop %edx ; ret", "pop eax ; pop ebp ; pop edx ; ret", "\x58\x5d\x5a\xc3", 4},
	{0, 0, "pop %eax ; pop %ebp ; pop %edi ; ret", "pop eax ; pop ebp ; pop edi ; ret", "\x58\x5d\x5f\xc3", 4},
	{0, 0, "pop %eax ; pop %ebp ; pop %esi ; ret", "pop eax ; pop ebp ; pop esi ; ret", "\x58\x5d\x5e\xc3", 4},
	{0, 0, "pop %eax ; pop %ebp ; pop %ebp ; ret", "pop eax ; pop ebp ; pop ebp ; ret", "\x58\x5d\x5d\xc3", 4},
	{0, 0, "pop %eax ; pop %ebp ; pop %esp ; ret", "pop eax ; pop ebp ; pop esp ; ret", "\x58\x5d\x5c\xc3", 4},
	{0, 0, "pop %eax ; pop %esp ; pop %eax ; ret", "pop eax ; pop esp ; pop eax ; ret", "\x58\x5c\x58\xc3", 4},
	{0, 0, "pop %eax ; pop %esp ; pop %ebx ; ret", "pop eax ; pop esp ; pop ebx ; ret", "\x58\x5c\x5b\xc3", 4},
	{0, 0, "pop %eax ; pop %esp ; pop %ecx ; ret", "pop eax ; pop esp ; pop ecx ; ret", "\x58\x5c\x59\xc3", 4},
	{0, 0, "pop %eax ; pop %esp ; pop %edx ; ret", "pop eax ; pop esp ; pop edx ; ret", "\x58\x5c\x5a\xc3", 4},
	{0, 0, "pop %eax ; pop %esp ; pop %edi ; ret", "pop eax ; pop esp ; pop edi ; ret", "\x58\x5c\x5f\xc3", 4},
	{0, 0, "pop %eax ; pop %esp ; pop %esi ; ret", "pop eax ; pop esp ; pop esi ; ret", "\x58\x5c\x5e\xc3", 4},
	{0, 0, "pop %eax ; pop %esp ; pop %ebp ; ret", "pop eax ; pop esp ; pop ebp ; ret", "\x58\x5c\x5d\xc3", 4},
	{0, 0, "pop %eax ; pop %esp ; pop %esp ; ret", "pop eax ; pop esp ; pop esp ; ret", "\x58\x5c\x5c\xc3", 4},
	{0, 0, "pop %ebx ; pop %eax ; pop %eax ; ret", "pop ebx ; pop eax ; pop eax ; ret", "\x5b\x58\x58\xc3", 4},
	{0, 0, "pop %ebx ; pop %eax ; pop %ebx ; ret", "pop ebx ; pop eax ; pop ebx ; ret", "\x5b\x58\x5b\xc3", 4},
	{0, 0, "pop %ebx ; pop %eax ; pop %ecx ; ret", "pop ebx ; pop eax ; pop ecx ; ret", "\x5b\x58\x59\xc3", 4},
	{0, 0, "pop %ebx ; pop %eax ; pop %edx ; ret", "pop ebx ; pop eax ; pop edx ; ret", "\x5b\x58\x5a\xc3", 4},
	{0, 0, "pop %ebx ; pop %eax ; pop %edi ; ret", "pop ebx ; pop eax ; pop edi ; ret", "\x5b\x58\x5f\xc3", 4},
	{0, 0, "pop %ebx ; pop %eax ; pop %esi ; ret", "pop ebx ; pop eax ; pop esi ; ret", "\x5b\x58\x5e\xc3", 4},
	{0, 0, "pop %ebx ; pop %eax ; pop %ebp ; ret", "pop ebx ; pop eax ; pop ebp ; ret", "\x5b\x58\x5d\xc3", 4},
	{0, 0, "pop %ebx ; pop %eax ; pop %esp ; ret", "pop ebx ; pop eax ; pop esp ; ret", "\x5b\x58\x5c\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebx ; pop %eax ; ret", "pop ebx ; pop ebx ; pop eax ; ret", "\x5b\x5b\x58\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebx ; pop %ebx ; ret", "pop ebx ; pop ebx ; pop ebx ; ret", "\x5b\x5b\x5b\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebx ; pop %ecx ; ret", "pop ebx ; pop ebx ; pop ecx ; ret", "\x5b\x5b\x59\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebx ; pop %edx ; ret", "pop ebx ; pop ebx ; pop edx ; ret", "\x5b\x5b\x5a\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebx ; pop %edi ; ret", "pop ebx ; pop ebx ; pop edi ; ret", "\x5b\x5b\x5f\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebx ; pop %esi ; ret", "pop ebx ; pop ebx ; pop esi ; ret", "\x5b\x5b\x5e\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebx ; pop %ebp ; ret", "pop ebx ; pop ebx ; pop ebp ; ret", "\x5b\x5b\x5d\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebx ; pop %esp ; ret", "pop ebx ; pop ebx ; pop esp ; ret", "\x5b\x5b\x5c\xc3", 4},
	{0, 0, "pop %ebx ; pop %ecx ; pop %eax ; ret", "pop ebx ; pop ecx ; pop eax ; ret", "\x5b\x59\x58\xc3", 4},
	{0, 0, "pop %ebx ; pop %ecx ; pop %ebx ; ret", "pop ebx ; pop ecx ; pop ebx ; ret", "\x5b\x59\x5b\xc3", 4},
	{0, 0, "pop %ebx ; pop %ecx ; pop %ecx ; ret", "pop ebx ; pop ecx ; pop ecx ; ret", "\x5b\x59\x59\xc3", 4},
	{0, 0, "pop %ebx ; pop %ecx ; pop %edx ; ret", "pop ebx ; pop ecx ; pop edx ; ret", "\x5b\x59\x5a\xc3", 4},
	{0, 0, "pop %ebx ; pop %ecx ; pop %edi ; ret", "pop ebx ; pop ecx ; pop edi ; ret", "\x5b\x59\x5f\xc3", 4},
	{0, 0, "pop %ebx ; pop %ecx ; pop %esi ; ret", "pop ebx ; pop ecx ; pop esi ; ret", "\x5b\x59\x5e\xc3", 4},
	{0, 0, "pop %ebx ; pop %ecx ; pop %ebp ; ret", "pop ebx ; pop ecx ; pop ebp ; ret", "\x5b\x59\x5d\xc3", 4},
	{0, 0, "pop %ebx ; pop %ecx ; pop %esp ; ret", "pop ebx ; pop ecx ; pop esp ; ret", "\x5b\x59\x5c\xc3", 4},
	{0, 0, "pop %ebx ; pop %edx ; pop %eax ; ret", "pop ebx ; pop edx ; pop eax ; ret", "\x5b\x5a\x58\xc3", 4},
	{0, 0, "pop %ebx ; pop %edx ; pop %ebx ; ret", "pop ebx ; pop edx ; pop ebx ; ret", "\x5b\x5a\x5b\xc3", 4},
	{0, 0, "pop %ebx ; pop %edx ; pop %ecx ; ret", "pop ebx ; pop edx ; pop ecx ; ret", "\x5b\x5a\x59\xc3", 4},
	{0, 0, "pop %ebx ; pop %edx ; pop %edx ; ret", "pop ebx ; pop edx ; pop edx ; ret", "\x5b\x5a\x5a\xc3", 4},
	{0, 0, "pop %ebx ; pop %edx ; pop %edi ; ret", "pop ebx ; pop edx ; pop edi ; ret", "\x5b\x5a\x5f\xc3", 4},
	{0, 0, "pop %ebx ; pop %edx ; pop %esi ; ret", "pop ebx ; pop edx ; pop esi ; ret", "\x5b\x5a\x5e\xc3", 4},
	{0, 0, "pop %ebx ; pop %edx ; pop %ebp ; ret", "pop ebx ; pop edx ; pop ebp ; ret", "\x5b\x5a\x5d\xc3", 4},
	{0, 0, "pop %ebx ; pop %edx ; pop %esp ; ret", "pop ebx ; pop edx ; pop esp ; ret", "\x5b\x5a\x5c\xc3", 4},
	{0, 0, "pop %ebx ; pop %edi ; pop %eax ; ret", "pop ebx ; pop edi ; pop eax ; ret", "\x5b\x5f\x58\xc3", 4},
	{0, 0, "pop %ebx ; pop %edi ; pop %ebx ; ret", "pop ebx ; pop edi ; pop ebx ; ret", "\x5b\x5f\x5b\xc3", 4},
	{0, 0, "pop %ebx ; pop %edi ; pop %ecx ; ret", "pop ebx ; pop edi ; pop ecx ; ret", "\x5b\x5f\x59\xc3", 4},
	{0, 0, "pop %ebx ; pop %edi ; pop %edx ; ret", "pop ebx ; pop edi ; pop edx ; ret", "\x5b\x5f\x5a\xc3", 4},
	{0, 0, "pop %ebx ; pop %edi ; pop %edi ; ret", "pop ebx ; pop edi ; pop edi ; ret", "\x5b\x5f\x5f\xc3", 4},
	{0, 0, "pop %ebx ; pop %edi ; pop %esi ; ret", "pop ebx ; pop edi ; pop esi ; ret", "\x5b\x5f\x5e\xc3", 4},
	{0, 0, "pop %ebx ; pop %edi ; pop %ebp ; ret", "pop ebx ; pop edi ; pop ebp ; ret", "\x5b\x5f\x5d\xc3", 4},
	{0, 0, "pop %ebx ; pop %edi ; pop %esp ; ret", "pop ebx ; pop edi ; pop esp ; ret", "\x5b\x5f\x5c\xc3", 4},
	{0, 0, "pop %ebx ; pop %esi ; pop %eax ; ret", "pop ebx ; pop esi ; pop eax ; ret", "\x5b\x5e\x58\xc3", 4},
	{0, 0, "pop %ebx ; pop %esi ; pop %ebx ; ret", "pop ebx ; pop esi ; pop ebx ; ret", "\x5b\x5e\x5b\xc3", 4},
	{0, 0, "pop %ebx ; pop %esi ; pop %ecx ; ret", "pop ebx ; pop esi ; pop ecx ; ret", "\x5b\x5e\x59\xc3", 4},
	{0, 0, "pop %ebx ; pop %esi ; pop %edx ; ret", "pop ebx ; pop esi ; pop edx ; ret", "\x5b\x5e\x5a\xc3", 4},
	{0, 0, "pop %ebx ; pop %esi ; pop %edi ; ret", "pop ebx ; pop esi ; pop edi ; ret", "\x5b\x5e\x5f\xc3", 4},
	{0, 0, "pop %ebx ; pop %esi ; pop %esi ; ret", "pop ebx ; pop esi ; pop esi ; ret", "\x5b\x5e\x5e\xc3", 4},
	{0, 0, "pop %ebx ; pop %esi ; pop %ebp ; ret", "pop ebx ; pop esi ; pop ebp ; ret", "\x5b\x5e\x5d\xc3", 4},
	{0, 0, "pop %ebx ; pop %esi ; pop %esp ; ret", "pop ebx ; pop esi ; pop esp ; ret", "\x5b\x5e\x5c\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebp ; pop %eax ; ret", "pop ebx ; pop ebp ; pop eax ; ret", "\x5b\x5d\x58\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebp ; pop %ebx ; ret", "pop ebx ; pop ebp ; pop ebx ; ret", "\x5b\x5d\x5b\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebp ; pop %ecx ; ret", "pop ebx ; pop ebp ; pop ecx ; ret", "\x5b\x5d\x59\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebp ; pop %edx ; ret", "pop ebx ; pop ebp ; pop edx ; ret", "\x5b\x5d\x5a\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebp ; pop %edi ; ret", "pop ebx ; pop ebp ; pop edi ; ret", "\x5b\x5d\x5f\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebp ; pop %esi ; ret", "pop ebx ; pop ebp ; pop esi ; ret", "\x5b\x5d\x5e\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebp ; pop %ebp ; ret", "pop ebx ; pop ebp ; pop ebp ; ret", "\x5b\x5d\x5d\xc3", 4},
	{0, 0, "pop %ebx ; pop %ebp ; pop %esp ; ret", "pop ebx ; pop ebp ; pop esp ; ret", "\x5b\x5d\x5c\xc3", 4},
	{0, 0, "pop %ebx ; pop %esp ; pop %eax ; ret", "pop ebx ; pop esp ; pop eax ; ret", "\x5b\x5c\x58\xc3", 4},
	{0, 0, "pop %ebx ; pop %esp ; pop %ebx ; ret", "pop ebx ; pop esp ; pop ebx ; ret", "\x5b\x5c\x5b\xc3", 4},
	{0, 0, "pop %ebx ; pop %esp ; pop %ecx ; ret", "pop ebx ; pop esp ; pop ecx ; ret", "\x5b\x5c\x59\xc3", 4},
	{0, 0, "pop %ebx ; pop %esp ; pop %edx ; ret", "pop ebx ; pop esp ; pop edx ; ret", "\x5b\x5c\x5a\xc3", 4},
	{0, 0, "pop %ebx ; pop %esp ; pop %edi ; ret", "pop ebx ; pop esp ; pop edi ; ret", "\x5b\x5c\x5f\xc3", 4},
	{0, 0, "pop %ebx ; pop %esp ; pop %esi ; ret", "pop ebx ; pop esp ; pop esi ; ret", "\x5b\x5c\x5e\xc3", 4},
	{0, 0, "pop %ebx ; pop %esp ; pop %ebp ; ret", "pop ebx ; pop esp ; pop ebp ; ret", "\x5b\x5c\x5d\xc3", 4},
	{0, 0, "pop %ebx ; pop %esp ; pop %esp ; ret", "pop ebx ; pop esp ; pop esp ; ret", "\x5b\x5c\x5c\xc3", 4},
	{0, 0, "pop %ecx ; pop %eax ; pop %eax ; ret", "pop ecx ; pop eax ; pop eax ; ret", "\x59\x58\x58\xc3", 4},
	{0, 0, "pop %ecx ; pop %eax ; pop %ebx ; ret", "pop ecx ; pop eax ; pop ebx ; ret", "\x59\x58\x5b\xc3", 4},
	{0, 0, "pop %ecx ; pop %eax ; pop %ecx ; ret", "pop ecx ; pop eax ; pop ecx ; ret", "\x59\x58\x59\xc3", 4},
	{0, 0, "pop %ecx ; pop %eax ; pop %edx ; ret", "pop ecx ; pop eax ; pop edx ; ret", "\x59\x58\x5a\xc3", 4},
	{0, 0, "pop %ecx ; pop %eax ; pop %edi ; ret", "pop ecx ; pop eax ; pop edi ; ret", "\x59\x58\x5f\xc3", 4},
	{0, 0, "pop %ecx ; pop %eax ; pop %esi ; ret", "pop ecx ; pop eax ; pop esi ; ret", "\x59\x58\x5e\xc3", 4},
	{0, 0, "pop %ecx ; pop %eax ; pop %ebp ; ret", "pop ecx ; pop eax ; pop ebp ; ret", "\x59\x58\x5d\xc3", 4},
	{0, 0, "pop %ecx ; pop %eax ; pop %esp ; ret", "pop ecx ; pop eax ; pop esp ; ret", "\x59\x58\x5c\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebx ; pop %eax ; ret", "pop ecx ; pop ebx ; pop eax ; ret", "\x59\x5b\x58\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebx ; pop %ebx ; ret", "pop ecx ; pop ebx ; pop ebx ; ret", "\x59\x5b\x5b\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebx ; pop %ecx ; ret", "pop ecx ; pop ebx ; pop ecx ; ret", "\x59\x5b\x59\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebx ; pop %edx ; ret", "pop ecx ; pop ebx ; pop edx ; ret", "\x59\x5b\x5a\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebx ; pop %edi ; ret", "pop ecx ; pop ebx ; pop edi ; ret", "\x59\x5b\x5f\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebx ; pop %esi ; ret", "pop ecx ; pop ebx ; pop esi ; ret", "\x59\x5b\x5e\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebx ; pop %ebp ; ret", "pop ecx ; pop ebx ; pop ebp ; ret", "\x59\x5b\x5d\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebx ; pop %esp ; ret", "pop ecx ; pop ebx ; pop esp ; ret", "\x59\x5b\x5c\xc3", 4},
	{0, 0, "pop %ecx ; pop %ecx ; pop %eax ; ret", "pop ecx ; pop ecx ; pop eax ; ret", "\x59\x59\x58\xc3", 4},
	{0, 0, "pop %ecx ; pop %ecx ; pop %ebx ; ret", "pop ecx ; pop ecx ; pop ebx ; ret", "\x59\x59\x5b\xc3", 4},
	{0, 0, "pop %ecx ; pop %ecx ; pop %ecx ; ret", "pop ecx ; pop ecx ; pop ecx ; ret", "\x59\x59\x59\xc3", 4},
	{0, 0, "pop %ecx ; pop %ecx ; pop %edx ; ret", "pop ecx ; pop ecx ; pop edx ; ret", "\x59\x59\x5a\xc3", 4},
	{0, 0, "pop %ecx ; pop %ecx ; pop %edi ; ret", "pop ecx ; pop ecx ; pop edi ; ret", "\x59\x59\x5f\xc3", 4},
	{0, 0, "pop %ecx ; pop %ecx ; pop %esi ; ret", "pop ecx ; pop ecx ; pop esi ; ret", "\x59\x59\x5e\xc3", 4},
	{0, 0, "pop %ecx ; pop %ecx ; pop %ebp ; ret", "pop ecx ; pop ecx ; pop ebp ; ret", "\x59\x59\x5d\xc3", 4},
	{0, 0, "pop %ecx ; pop %ecx ; pop %esp ; ret", "pop ecx ; pop ecx ; pop esp ; ret", "\x59\x59\x5c\xc3", 4},
	{0, 0, "pop %ecx ; pop %edx ; pop %eax ; ret", "pop ecx ; pop edx ; pop eax ; ret", "\x59\x5a\x58\xc3", 4},
	{0, 0, "pop %ecx ; pop %edx ; pop %ebx ; ret", "pop ecx ; pop edx ; pop ebx ; ret", "\x59\x5a\x5b\xc3", 4},
	{0, 0, "pop %ecx ; pop %edx ; pop %ecx ; ret", "pop ecx ; pop edx ; pop ecx ; ret", "\x59\x5a\x59\xc3", 4},
	{0, 0, "pop %ecx ; pop %edx ; pop %edx ; ret", "pop ecx ; pop edx ; pop edx ; ret", "\x59\x5a\x5a\xc3", 4},
	{0, 0, "pop %ecx ; pop %edx ; pop %edi ; ret", "pop ecx ; pop edx ; pop edi ; ret", "\x59\x5a\x5f\xc3", 4},
	{0, 0, "pop %ecx ; pop %edx ; pop %esi ; ret", "pop ecx ; pop edx ; pop esi ; ret", "\x59\x5a\x5e\xc3", 4},
	{0, 0, "pop %ecx ; pop %edx ; pop %ebp ; ret", "pop ecx ; pop edx ; pop ebp ; ret", "\x59\x5a\x5d\xc3", 4},
	{0, 0, "pop %ecx ; pop %edx ; pop %esp ; ret", "pop ecx ; pop edx ; pop esp ; ret", "\x59\x5a\x5c\xc3", 4},
	{0, 0, "pop %ecx ; pop %edi ; pop %eax ; ret", "pop ecx ; pop edi ; pop eax ; ret", "\x59\x5f\x58\xc3", 4},
	{0, 0, "pop %ecx ; pop %edi ; pop %ebx ; ret", "pop ecx ; pop edi ; pop ebx ; ret", "\x59\x5f\x5b\xc3", 4},
	{0, 0, "pop %ecx ; pop %edi ; pop %ecx ; ret", "pop ecx ; pop edi ; pop ecx ; ret", "\x59\x5f\x59\xc3", 4},
	{0, 0, "pop %ecx ; pop %edi ; pop %edx ; ret", "pop ecx ; pop edi ; pop edx ; ret", "\x59\x5f\x5a\xc3", 4},
	{0, 0, "pop %ecx ; pop %edi ; pop %edi ; ret", "pop ecx ; pop edi ; pop edi ; ret", "\x59\x5f\x5f\xc3", 4},
	{0, 0, "pop %ecx ; pop %edi ; pop %esi ; ret", "pop ecx ; pop edi ; pop esi ; ret", "\x59\x5f\x5e\xc3", 4},
	{0, 0, "pop %ecx ; pop %edi ; pop %ebp ; ret", "pop ecx ; pop edi ; pop ebp ; ret", "\x59\x5f\x5d\xc3", 4},
	{0, 0, "pop %ecx ; pop %edi ; pop %esp ; ret", "pop ecx ; pop edi ; pop esp ; ret", "\x59\x5f\x5c\xc3", 4},
	{0, 0, "pop %ecx ; pop %esi ; pop %eax ; ret", "pop ecx ; pop esi ; pop eax ; ret", "\x59\x5e\x58\xc3", 4},
	{0, 0, "pop %ecx ; pop %esi ; pop %ebx ; ret", "pop ecx ; pop esi ; pop ebx ; ret", "\x59\x5e\x5b\xc3", 4},
	{0, 0, "pop %ecx ; pop %esi ; pop %ecx ; ret", "pop ecx ; pop esi ; pop ecx ; ret", "\x59\x5e\x59\xc3", 4},
	{0, 0, "pop %ecx ; pop %esi ; pop %edx ; ret", "pop ecx ; pop esi ; pop edx ; ret", "\x59\x5e\x5a\xc3", 4},
	{0, 0, "pop %ecx ; pop %esi ; pop %edi ; ret", "pop ecx ; pop esi ; pop edi ; ret", "\x59\x5e\x5f\xc3", 4},
	{0, 0, "pop %ecx ; pop %esi ; pop %esi ; ret", "pop ecx ; pop esi ; pop esi ; ret", "\x59\x5e\x5e\xc3", 4},
	{0, 0, "pop %ecx ; pop %esi ; pop %ebp ; ret", "pop ecx ; pop esi ; pop ebp ; ret", "\x59\x5e\x5d\xc3", 4},
	{0, 0, "pop %ecx ; pop %esi ; pop %esp ; ret", "pop ecx ; pop esi ; pop esp ; ret", "\x59\x5e\x5c\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebp ; pop %eax ; ret", "pop ecx ; pop ebp ; pop eax ; ret", "\x59\x5d\x58\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebp ; pop %ebx ; ret", "pop ecx ; pop ebp ; pop ebx ; ret", "\x59\x5d\x5b\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebp ; pop %ecx ; ret", "pop ecx ; pop ebp ; pop ecx ; ret", "\x59\x5d\x59\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebp ; pop %edx ; ret", "pop ecx ; pop ebp ; pop edx ; ret", "\x59\x5d\x5a\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebp ; pop %edi ; ret", "pop ecx ; pop ebp ; pop edi ; ret", "\x59\x5d\x5f\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebp ; pop %esi ; ret", "pop ecx ; pop ebp ; pop esi ; ret", "\x59\x5d\x5e\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebp ; pop %ebp ; ret", "pop ecx ; pop ebp ; pop ebp ; ret", "\x59\x5d\x5d\xc3", 4},
	{0, 0, "pop %ecx ; pop %ebp ; pop %esp ; ret", "pop ecx ; pop ebp ; pop esp ; ret", "\x59\x5d\x5c\xc3", 4},
	{0, 0, "pop %ecx ; pop %esp ; pop %eax ; ret", "pop ecx ; pop esp ; pop eax ; ret", "\x59\x5c\x58\xc3", 4},
	{0, 0, "pop %ecx ; pop %esp ; pop %ebx ; ret", "pop ecx ; pop esp ; pop ebx ; ret", "\x59\x5c\x5b\xc3", 4},
	{0, 0, "pop %ecx ; pop %esp ; pop %ecx ; ret", "pop ecx ; pop esp ; pop ecx ; ret", "\x59\x5c\x59\xc3", 4},
	{0, 0, "pop %ecx ; pop %esp ; pop %edx ; ret", "pop ecx ; pop esp ; pop edx ; ret", "\x59\x5c\x5a\xc3", 4},
	{0, 0, "pop %ecx ; pop %esp ; pop %edi ; ret", "pop ecx ; pop esp ; pop edi ; ret", "\x59\x5c\x5f\xc3", 4},
	{0, 0, "pop %ecx ; pop %esp ; pop %esi ; ret", "pop ecx ; pop esp ; pop esi ; ret", "\x59\x5c\x5e\xc3", 4},
	{0, 0, "pop %ecx ; pop %esp ; pop %ebp ; ret", "pop ecx ; pop esp ; pop ebp ; ret", "\x59\x5c\x5d\xc3", 4},
	{0, 0, "pop %ecx ; pop %esp ; pop %esp ; ret", "pop ecx ; pop esp ; pop esp ; ret", "\x59\x5c\x5c\xc3", 4},
	{0, 0, "pop %edx ; pop %eax ; pop %eax ; ret", "pop edx ; pop eax ; pop eax ; ret", "\x5a\x58\x58\xc3", 4},
	{0, 0, "pop %edx ; pop %eax ; pop %ebx ; ret", "pop edx ; pop eax ; pop ebx ; ret", "\x5a\x58\x5b\xc3", 4},
	{0, 0, "pop %edx ; pop %eax ; pop %ecx ; ret", "pop edx ; pop eax ; pop ecx ; ret", "\x5a\x58\x59\xc3", 4},
	{0, 0, "pop %edx ; pop %eax ; pop %edx ; ret", "pop edx ; pop eax ; pop edx ; ret", "\x5a\x58\x5a\xc3", 4},
	{0, 0, "pop %edx ; pop %eax ; pop %edi ; ret", "pop edx ; pop eax ; pop edi ; ret", "\x5a\x58\x5f\xc3", 4},
	{0, 0, "pop %edx ; pop %eax ; pop %esi ; ret", "pop edx ; pop eax ; pop esi ; ret", "\x5a\x58\x5e\xc3", 4},
	{0, 0, "pop %edx ; pop %eax ; pop %ebp ; ret", "pop edx ; pop eax ; pop ebp ; ret", "\x5a\x58\x5d\xc3", 4},
	{0, 0, "pop %edx ; pop %eax ; pop %esp ; ret", "pop edx ; pop eax ; pop esp ; ret", "\x5a\x58\x5c\xc3", 4},
	{0, 0, "pop %edx ; pop %ebx ; pop %eax ; ret", "pop edx ; pop ebx ; pop eax ; ret", "\x5a\x5b\x58\xc3", 4},
	{0, 0, "pop %edx ; pop %ebx ; pop %ebx ; ret", "pop edx ; pop ebx ; pop ebx ; ret", "\x5a\x5b\x5b\xc3", 4},
	{0, 0, "pop %edx ; pop %ebx ; pop %ecx ; ret", "pop edx ; pop ebx ; pop ecx ; ret", "\x5a\x5b\x59\xc3", 4},
	{0, 0, "pop %edx ; pop %ebx ; pop %edx ; ret", "pop edx ; pop ebx ; pop edx ; ret", "\x5a\x5b\x5a\xc3", 4},
	{0, 0, "pop %edx ; pop %ebx ; pop %edi ; ret", "pop edx ; pop ebx ; pop edi ; ret", "\x5a\x5b\x5f\xc3", 4},
	{0, 0, "pop %edx ; pop %ebx ; pop %esi ; ret", "pop edx ; pop ebx ; pop esi ; ret", "\x5a\x5b\x5e\xc3", 4},
	{0, 0, "pop %edx ; pop %ebx ; pop %ebp ; ret", "pop edx ; pop ebx ; pop ebp ; ret", "\x5a\x5b\x5d\xc3", 4},
	{0, 0, "pop %edx ; pop %ebx ; pop %esp ; ret", "pop edx ; pop ebx ; pop esp ; ret", "\x5a\x5b\x5c\xc3", 4},
	{0, 0, "pop %edx ; pop %ecx ; pop %eax ; ret", "pop edx ; pop ecx ; pop eax ; ret", "\x5a\x59\x58\xc3", 4},
	{0, 0, "pop %edx ; pop %ecx ; pop %ebx ; ret", "pop edx ; pop ecx ; pop ebx ; ret", "\x5a\x59\x5b\xc3", 4},
	{0, 0, "pop %edx ; pop %ecx ; pop %ecx ; ret", "pop edx ; pop ecx ; pop ecx ; ret", "\x5a\x59\x59\xc3", 4},
	{0, 0, "pop %edx ; pop %ecx ; pop %edx ; ret", "pop edx ; pop ecx ; pop edx ; ret", "\x5a\x59\x5a\xc3", 4},
	{0, 0, "pop %edx ; pop %ecx ; pop %edi ; ret", "pop edx ; pop ecx ; pop edi ; ret", "\x5a\x59\x5f\xc3", 4},
	{0, 0, "pop %edx ; pop %ecx ; pop %esi ; ret", "pop edx ; pop ecx ; pop esi ; ret", "\x5a\x59\x5e\xc3", 4},
	{0, 0, "pop %edx ; pop %ecx ; pop %ebp ; ret", "pop edx ; pop ecx ; pop ebp ; ret", "\x5a\x59\x5d\xc3", 4},
	{0, 0, "pop %edx ; pop %ecx ; pop %esp ; ret", "pop edx ; pop ecx ; pop esp ; ret", "\x5a\x59\x5c\xc3", 4},
	{0, 0, "pop %edx ; pop %edx ; pop %eax ; ret", "pop edx ; pop edx ; pop eax ; ret", "\x5a\x5a\x58\xc3", 4},
	{0, 0, "pop %edx ; pop %edx ; pop %ebx ; ret", "pop edx ; pop edx ; pop ebx ; ret", "\x5a\x5a\x5b\xc3", 4},
	{0, 0, "pop %edx ; pop %edx ; pop %ecx ; ret", "pop edx ; pop edx ; pop ecx ; ret", "\x5a\x5a\x59\xc3", 4},
	{0, 0, "pop %edx ; pop %edx ; pop %edx ; ret", "pop edx ; pop edx ; pop edx ; ret", "\x5a\x5a\x5a\xc3", 4},
	{0, 0, "pop %edx ; pop %edx ; pop %edi ; ret", "pop edx ; pop edx ; pop edi ; ret", "\x5a\x5a\x5f\xc3", 4},
	{0, 0, "pop %edx ; pop %edx ; pop %esi ; ret", "pop edx ; pop edx ; pop esi ; ret", "\x5a\x5a\x5e\xc3", 4},
	{0, 0, "pop %edx ; pop %edx ; pop %ebp ; ret", "pop edx ; pop edx ; pop ebp ; ret", "\x5a\x5a\x5d\xc3", 4},
	{0, 0, "pop %edx ; pop %edx ; pop %esp ; ret", "pop edx ; pop edx ; pop esp ; ret", "\x5a\x5a\x5c\xc3", 4},
	{0, 0, "pop %edx ; pop %edi ; pop %eax ; ret", "pop edx ; pop edi ; pop eax ; ret", "\x5a\x5f\x58\xc3", 4},
	{0, 0, "pop %edx ; pop %edi ; pop %ebx ; ret", "pop edx ; pop edi ; pop ebx ; ret", "\x5a\x5f\x5b\xc3", 4},
	{0, 0, "pop %edx ; pop %edi ; pop %ecx ; ret", "pop edx ; pop edi ; pop ecx ; ret", "\x5a\x5f\x59\xc3", 4},
	{0, 0, "pop %edx ; pop %edi ; pop %edx ; ret", "pop edx ; pop edi ; pop edx ; ret", "\x5a\x5f\x5a\xc3", 4},
	{0, 0, "pop %edx ; pop %edi ; pop %edi ; ret", "pop edx ; pop edi ; pop edi ; ret", "\x5a\x5f\x5f\xc3", 4},
	{0, 0, "pop %edx ; pop %edi ; pop %esi ; ret", "pop edx ; pop edi ; pop esi ; ret", "\x5a\x5f\x5e\xc3", 4},
	{0, 0, "pop %edx ; pop %edi ; pop %ebp ; ret", "pop edx ; pop edi ; pop ebp ; ret", "\x5a\x5f\x5d\xc3", 4},
	{0, 0, "pop %edx ; pop %edi ; pop %esp ; ret", "pop edx ; pop edi ; pop esp ; ret", "\x5a\x5f\x5c\xc3", 4},
	{0, 0, "pop %edx ; pop %esi ; pop %eax ; ret", "pop edx ; pop esi ; pop eax ; ret", "\x5a\x5e\x58\xc3", 4},
	{0, 0, "pop %edx ; pop %esi ; pop %ebx ; ret", "pop edx ; pop esi ; pop ebx ; ret", "\x5a\x5e\x5b\xc3", 4},
	{0, 0, "pop %edx ; pop %esi ; pop %ecx ; ret", "pop edx ; pop esi ; pop ecx ; ret", "\x5a\x5e\x59\xc3", 4},
	{0, 0, "pop %edx ; pop %esi ; pop %edx ; ret", "pop edx ; pop esi ; pop edx ; ret", "\x5a\x5e\x5a\xc3", 4},
	{0, 0, "pop %edx ; pop %esi ; pop %edi ; ret", "pop edx ; pop esi ; pop edi ; ret", "\x5a\x5e\x5f\xc3", 4},
	{0, 0, "pop %edx ; pop %esi ; pop %esi ; ret", "pop edx ; pop esi ; pop esi ; ret", "\x5a\x5e\x5e\xc3", 4},
	{0, 0, "pop %edx ; pop %esi ; pop %ebp ; ret", "pop edx ; pop esi ; pop ebp ; ret", "\x5a\x5e\x5d\xc3", 4},
	{0, 0, "pop %edx ; pop %esi ; pop %esp ; ret", "pop edx ; pop esi ; pop esp ; ret", "\x5a\x5e\x5c\xc3", 4},
	{0, 0, "pop %edx ; pop %ebp ; pop %eax ; ret", "pop edx ; pop ebp ; pop eax ; ret", "\x5a\x5d\x58\xc3", 4},
	{0, 0, "pop %edx ; pop %ebp ; pop %ebx ; ret", "pop edx ; pop ebp ; pop ebx ; ret", "\x5a\x5d\x5b\xc3", 4},
	{0, 0, "pop %edx ; pop %ebp ; pop %ecx ; ret", "pop edx ; pop ebp ; pop ecx ; ret", "\x5a\x5d\x59\xc3", 4},
	{0, 0, "pop %edx ; pop %ebp ; pop %edx ; ret", "pop edx ; pop ebp ; pop edx ; ret", "\x5a\x5d\x5a\xc3", 4},
	{0, 0, "pop %edx ; pop %ebp ; pop %edi ; ret", "pop edx ; pop ebp ; pop edi ; ret", "\x5a\x5d\x5f\xc3", 4},
	{0, 0, "pop %edx ; pop %ebp ; pop %esi ; ret", "pop edx ; pop ebp ; pop esi ; ret", "\x5a\x5d\x5e\xc3", 4},
	{0, 0, "pop %edx ; pop %ebp ; pop %ebp ; ret", "pop edx ; pop ebp ; pop ebp ; ret", "\x5a\x5d\x5d\xc3", 4},
	{0, 0, "pop %edx ; pop %ebp ; pop %esp ; ret", "pop edx ; pop ebp ; pop esp ; ret", "\x5a\x5d\x5c\xc3", 4},
	{0, 0, "pop %edx ; pop %esp ; pop %eax ; ret", "pop edx ; pop esp ; pop eax ; ret", "\x5a\x5c\x58\xc3", 4},
	{0, 0, "pop %edx ; pop %esp ; pop %ebx ; ret", "pop edx ; pop esp ; pop ebx ; ret", "\x5a\x5c\x5b\xc3", 4},
	{0, 0, "pop %edx ; pop %esp ; pop %ecx ; ret", "pop edx ; pop esp ; pop ecx ; ret", "\x5a\x5c\x59\xc3", 4},
	{0, 0, "pop %edx ; pop %esp ; pop %edx ; ret", "pop edx ; pop esp ; pop edx ; ret", "\x5a\x5c\x5a\xc3", 4},
	{0, 0, "pop %edx ; pop %esp ; pop %edi ; ret", "pop edx ; pop esp ; pop edi ; ret", "\x5a\x5c\x5f\xc3", 4},
	{0, 0, "pop %edx ; pop %esp ; pop %esi ; ret", "pop edx ; pop esp ; pop esi ; ret", "\x5a\x5c\x5e\xc3", 4},
	{0, 0, "pop %edx ; pop %esp ; pop %ebp ; ret", "pop edx ; pop esp ; pop ebp ; ret", "\x5a\x5c\x5d\xc3", 4},
	{0, 0, "pop %edx ; pop %esp ; pop %esp ; ret", "pop edx ; pop esp ; pop esp ; ret", "\x5a\x5c\x5c\xc3", 4},
	{0, 0, "pop %edi ; pop %eax ; pop %eax ; ret", "pop edi ; pop eax ; pop eax ; ret", "\x5f\x58\x58\xc3", 4},
	{0, 0, "pop %edi ; pop %eax ; pop %ebx ; ret", "pop edi ; pop eax ; pop ebx ; ret", "\x5f\x58\x5b\xc3", 4},
	{0, 0, "pop %edi ; pop %eax ; pop %ecx ; ret", "pop edi ; pop eax ; pop ecx ; ret", "\x5f\x58\x59\xc3", 4},
	{0, 0, "pop %edi ; pop %eax ; pop %edx ; ret", "pop edi ; pop eax ; pop edx ; ret", "\x5f\x58\x5a\xc3", 4},
	{0, 0, "pop %edi ; pop %eax ; pop %edi ; ret", "pop edi ; pop eax ; pop edi ; ret", "\x5f\x58\x5f\xc3", 4},
	{0, 0, "pop %edi ; pop %eax ; pop %esi ; ret", "pop edi ; pop eax ; pop esi ; ret", "\x5f\x58\x5e\xc3", 4},
	{0, 0, "pop %edi ; pop %eax ; pop %ebp ; ret", "pop edi ; pop eax ; pop ebp ; ret", "\x5f\x58\x5d\xc3", 4},
	{0, 0, "pop %edi ; pop %eax ; pop %esp ; ret", "pop edi ; pop eax ; pop esp ; ret", "\x5f\x58\x5c\xc3", 4},
	{0, 0, "pop %edi ; pop %ebx ; pop %eax ; ret", "pop edi ; pop ebx ; pop eax ; ret", "\x5f\x5b\x58\xc3", 4},
	{0, 0, "pop %edi ; pop %ebx ; pop %ebx ; ret", "pop edi ; pop ebx ; pop ebx ; ret", "\x5f\x5b\x5b\xc3", 4},
	{0, 0, "pop %edi ; pop %ebx ; pop %ecx ; ret", "pop edi ; pop ebx ; pop ecx ; ret", "\x5f\x5b\x59\xc3", 4},
	{0, 0, "pop %edi ; pop %ebx ; pop %edx ; ret", "pop edi ; pop ebx ; pop edx ; ret", "\x5f\x5b\x5a\xc3", 4},
	{0, 0, "pop %edi ; pop %ebx ; pop %edi ; ret", "pop edi ; pop ebx ; pop edi ; ret", "\x5f\x5b\x5f\xc3", 4},
	{0, 0, "pop %edi ; pop %ebx ; pop %esi ; ret", "pop edi ; pop ebx ; pop esi ; ret", "\x5f\x5b\x5e\xc3", 4},
	{0, 0, "pop %edi ; pop %ebx ; pop %ebp ; ret", "pop edi ; pop ebx ; pop ebp ; ret", "\x5f\x5b\x5d\xc3", 4},
	{0, 0, "pop %edi ; pop %ebx ; pop %esp ; ret", "pop edi ; pop ebx ; pop esp ; ret", "\x5f\x5b\x5c\xc3", 4},
	{0, 0, "pop %edi ; pop %ecx ; pop %eax ; ret", "pop edi ; pop ecx ; pop eax ; ret", "\x5f\x59\x58\xc3", 4},
	{0, 0, "pop %edi ; pop %ecx ; pop %ebx ; ret", "pop edi ; pop ecx ; pop ebx ; ret", "\x5f\x59\x5b\xc3", 4},
	{0, 0, "pop %edi ; pop %ecx ; pop %ecx ; ret", "pop edi ; pop ecx ; pop ecx ; ret", "\x5f\x59\x59\xc3", 4},
	{0, 0, "pop %edi ; pop %ecx ; pop %edx ; ret", "pop edi ; pop ecx ; pop edx ; ret", "\x5f\x59\x5a\xc3", 4},
	{0, 0, "pop %edi ; pop %ecx ; pop %edi ; ret", "pop edi ; pop ecx ; pop edi ; ret", "\x5f\x59\x5f\xc3", 4},
	{0, 0, "pop %edi ; pop %ecx ; pop %esi ; ret", "pop edi ; pop ecx ; pop esi ; ret", "\x5f\x59\x5e\xc3", 4},
	{0, 0, "pop %edi ; pop %ecx ; pop %ebp ; ret", "pop edi ; pop ecx ; pop ebp ; ret", "\x5f\x59\x5d\xc3", 4},
	{0, 0, "pop %edi ; pop %ecx ; pop %esp ; ret", "pop edi ; pop ecx ; pop esp ; ret", "\x5f\x59\x5c\xc3", 4},
	{0, 0, "pop %edi ; pop %edx ; pop %eax ; ret", "pop edi ; pop edx ; pop eax ; ret", "\x5f\x5a\x58\xc3", 4},
	{0, 0, "pop %edi ; pop %edx ; pop %ebx ; ret", "pop edi ; pop edx ; pop ebx ; ret", "\x5f\x5a\x5b\xc3", 4},
	{0, 0, "pop %edi ; pop %edx ; pop %ecx ; ret", "pop edi ; pop edx ; pop ecx ; ret", "\x5f\x5a\x59\xc3", 4},
	{0, 0, "pop %edi ; pop %edx ; pop %edx ; ret", "pop edi ; pop edx ; pop edx ; ret", "\x5f\x5a\x5a\xc3", 4},
	{0, 0, "pop %edi ; pop %edx ; pop %edi ; ret", "pop edi ; pop edx ; pop edi ; ret", "\x5f\x5a\x5f\xc3", 4},
	{0, 0, "pop %edi ; pop %edx ; pop %esi ; ret", "pop edi ; pop edx ; pop esi ; ret", "\x5f\x5a\x5e\xc3", 4},
	{0, 0, "pop %edi ; pop %edx ; pop %ebp ; ret", "pop edi ; pop edx ; pop ebp ; ret", "\x5f\x5a\x5d\xc3", 4},
	{0, 0, "pop %edi ; pop %edx ; pop %esp ; ret", "pop edi ; pop edx ; pop esp ; ret", "\x5f\x5a\x5c\xc3", 4},
	{0, 0, "pop %edi ; pop %edi ; pop %eax ; ret", "pop edi ; pop edi ; pop eax ; ret", "\x5f\x5f\x58\xc3", 4},
	{0, 0, "pop %edi ; pop %edi ; pop %ebx ; ret", "pop edi ; pop edi ; pop ebx ; ret", "\x5f\x5f\x5b\xc3", 4},
	{0, 0, "pop %edi ; pop %edi ; pop %ecx ; ret", "pop edi ; pop edi ; pop ecx ; ret", "\x5f\x5f\x59\xc3", 4},
	{0, 0, "pop %edi ; pop %edi ; pop %edx ; ret", "pop edi ; pop edi ; pop edx ; ret", "\x5f\x5f\x5a\xc3", 4},
	{0, 0, "pop %edi ; pop %edi ; pop %edi ; ret", "pop edi ; pop edi ; pop edi ; ret", "\x5f\x5f\x5f\xc3", 4},
	{0, 0, "pop %edi ; pop %edi ; pop %esi ; ret", "pop edi ; pop edi ; pop esi ; ret", "\x5f\x5f\x5e\xc3", 4},
	{0, 0, "pop %edi ; pop %edi ; pop %ebp ; ret", "pop edi ; pop edi ; pop ebp ; ret", "\x5f\x5f\x5d\xc3", 4},
	{0, 0, "pop %edi ; pop %edi ; pop %esp ; ret", "pop edi ; pop edi ; pop esp ; ret", "\x5f\x5f\x5c\xc3", 4},
	{0, 0, "pop %edi ; pop %esi ; pop %eax ; ret", "pop edi ; pop esi ; pop eax ; ret", "\x5f\x5e\x58\xc3", 4},
	{0, 0, "pop %edi ; pop %esi ; pop %ebx ; ret", "pop edi ; pop esi ; pop ebx ; ret", "\x5f\x5e\x5b\xc3", 4},
	{0, 0, "pop %edi ; pop %esi ; pop %ecx ; ret", "pop edi ; pop esi ; pop ecx ; ret", "\x5f\x5e\x59\xc3", 4},
	{0, 0, "pop %edi ; pop %esi ; pop %edx ; ret", "pop edi ; pop esi ; pop edx ; ret", "\x5f\x5e\x5a\xc3", 4},
	{0, 0, "pop %edi ; pop %esi ; pop %edi ; ret", "pop edi ; pop esi ; pop edi ; ret", "\x5f\x5e\x5f\xc3", 4},
	{0, 0, "pop %edi ; pop %esi ; pop %esi ; ret", "pop edi ; pop esi ; pop esi ; ret", "\x5f\x5e\x5e\xc3", 4},
	{0, 0, "pop %edi ; pop %esi ; pop %ebp ; ret", "pop edi ; pop esi ; pop ebp ; ret", "\x5f\x5e\x5d\xc3", 4},
	{0, 0, "pop %edi ; pop %esi ; pop %esp ; ret", "pop edi ; pop esi ; pop esp ; ret", "\x5f\x5e\x5c\xc3", 4},
	{0, 0, "pop %edi ; pop %ebp ; pop %eax ; ret", "pop edi ; pop ebp ; pop eax ; ret", "\x5f\x5d\x58\xc3", 4},
	{0, 0, "pop %edi ; pop %ebp ; pop %ebx ; ret", "pop edi ; pop ebp ; pop ebx ; ret", "\x5f\x5d\x5b\xc3", 4},
	{0, 0, "pop %edi ; pop %ebp ; pop %ecx ; ret", "pop edi ; pop ebp ; pop ecx ; ret", "\x5f\x5d\x59\xc3", 4},
	{0, 0, "pop %edi ; pop %ebp ; pop %edx ; ret", "pop edi ; pop ebp ; pop edx ; ret", "\x5f\x5d\x5a\xc3", 4},
	{0, 0, "pop %edi ; pop %ebp ; pop %edi ; ret", "pop edi ; pop ebp ; pop edi ; ret", "\x5f\x5d\x5f\xc3", 4},
	{0, 0, "pop %edi ; pop %ebp ; pop %esi ; ret", "pop edi ; pop ebp ; pop esi ; ret", "\x5f\x5d\x5e\xc3", 4},
	{0, 0, "pop %edi ; pop %ebp ; pop %ebp ; ret", "pop edi ; pop ebp ; pop ebp ; ret", "\x5f\x5d\x5d\xc3", 4},
	{0, 0, "pop %edi ; pop %ebp ; pop %esp ; ret", "pop edi ; pop ebp ; pop esp ; ret", "\x5f\x5d\x5c\xc3", 4},
	{0, 0, "pop %edi ; pop %esp ; pop %eax ; ret", "pop edi ; pop esp ; pop eax ; ret", "\x5f\x5c\x58\xc3", 4},
	{0, 0, "pop %edi ; pop %esp ; pop %ebx ; ret", "pop edi ; pop esp ; pop ebx ; ret", "\x5f\x5c\x5b\xc3", 4},
	{0, 0, "pop %edi ; pop %esp ; pop %ecx ; ret", "pop edi ; pop esp ; pop ecx ; ret", "\x5f\x5c\x59\xc3", 4},
	{0, 0, "pop %edi ; pop %esp ; pop %edx ; ret", "pop edi ; pop esp ; pop edx ; ret", "\x5f\x5c\x5a\xc3", 4},
	{0, 0, "pop %edi ; pop %esp ; pop %edi ; ret", "pop edi ; pop esp ; pop edi ; ret", "\x5f\x5c\x5f\xc3", 4},
	{0, 0, "pop %edi ; pop %esp ; pop %esi ; ret", "pop edi ; pop esp ; pop esi ; ret", "\x5f\x5c\x5e\xc3", 4},
	{0, 0, "pop %edi ; pop %esp ; pop %ebp ; ret", "pop edi ; pop esp ; pop ebp ; ret", "\x5f\x5c\x5d\xc3", 4},
	{0, 0, "pop %edi ; pop %esp ; pop %esp ; ret", "pop edi ; pop esp ; pop esp ; ret", "\x5f\x5c\x5c\xc3", 4},
	{0, 0, "pop %esi ; pop %eax ; pop %eax ; ret", "pop esi ; pop eax ; pop eax ; ret", "\x5e\x58\x58\xc3", 4},
	{0, 0, "pop %esi ; pop %eax ; pop %ebx ; ret", "pop esi ; pop eax ; pop ebx ; ret", "\x5e\x58\x5b\xc3", 4},
	{0, 0, "pop %esi ; pop %eax ; pop %ecx ; ret", "pop esi ; pop eax ; pop ecx ; ret", "\x5e\x58\x59\xc3", 4},
	{0, 0, "pop %esi ; pop %eax ; pop %edx ; ret", "pop esi ; pop eax ; pop edx ; ret", "\x5e\x58\x5a\xc3", 4},
	{0, 0, "pop %esi ; pop %eax ; pop %edi ; ret", "pop esi ; pop eax ; pop edi ; ret", "\x5e\x58\x5f\xc3", 4},
	{0, 0, "pop %esi ; pop %eax ; pop %esi ; ret", "pop esi ; pop eax ; pop esi ; ret", "\x5e\x58\x5e\xc3", 4},
	{0, 0, "pop %esi ; pop %eax ; pop %ebp ; ret", "pop esi ; pop eax ; pop ebp ; ret", "\x5e\x58\x5d\xc3", 4},
	{0, 0, "pop %esi ; pop %eax ; pop %esp ; ret", "pop esi ; pop eax ; pop esp ; ret", "\x5e\x58\x5c\xc3", 4},
	{0, 0, "pop %esi ; pop %ebx ; pop %eax ; ret", "pop esi ; pop ebx ; pop eax ; ret", "\x5e\x5b\x58\xc3", 4},
	{0, 0, "pop %esi ; pop %ebx ; pop %ebx ; ret", "pop esi ; pop ebx ; pop ebx ; ret", "\x5e\x5b\x5b\xc3", 4},
	{0, 0, "pop %esi ; pop %ebx ; pop %ecx ; ret", "pop esi ; pop ebx ; pop ecx ; ret", "\x5e\x5b\x59\xc3", 4},
	{0, 0, "pop %esi ; pop %ebx ; pop %edx ; ret", "pop esi ; pop ebx ; pop edx ; ret", "\x5e\x5b\x5a\xc3", 4},
	{0, 0, "pop %esi ; pop %ebx ; pop %edi ; ret", "pop esi ; pop ebx ; pop edi ; ret", "\x5e\x5b\x5f\xc3", 4},
	{0, 0, "pop %esi ; pop %ebx ; pop %esi ; ret", "pop esi ; pop ebx ; pop esi ; ret", "\x5e\x5b\x5e\xc3", 4},
	{0, 0, "pop %esi ; pop %ebx ; pop %ebp ; ret", "pop esi ; pop ebx ; pop ebp ; ret", "\x5e\x5b\x5d\xc3", 4},
	{0, 0, "pop %esi ; pop %ebx ; pop %esp ; ret", "pop esi ; pop ebx ; pop esp ; ret", "\x5e\x5b\x5c\xc3", 4},
	{0, 0, "pop %esi ; pop %ecx ; pop %eax ; ret", "pop esi ; pop ecx ; pop eax ; ret", "\x5e\x59\x58\xc3", 4},
	{0, 0, "pop %esi ; pop %ecx ; pop %ebx ; ret", "pop esi ; pop ecx ; pop ebx ; ret", "\x5e\x59\x5b\xc3", 4},
	{0, 0, "pop %esi ; pop %ecx ; pop %ecx ; ret", "pop esi ; pop ecx ; pop ecx ; ret", "\x5e\x59\x59\xc3", 4},
	{0, 0, "pop %esi ; pop %ecx ; pop %edx ; ret", "pop esi ; pop ecx ; pop edx ; ret", "\x5e\x59\x5a\xc3", 4},
	{0, 0, "pop %esi ; pop %ecx ; pop %edi ; ret", "pop esi ; pop ecx ; pop edi ; ret", "\x5e\x59\x5f\xc3", 4},
	{0, 0, "pop %esi ; pop %ecx ; pop %esi ; ret", "pop esi ; pop ecx ; pop esi ; ret", "\x5e\x59\x5e\xc3", 4},
	{0, 0, "pop %esi ; pop %ecx ; pop %ebp ; ret", "pop esi ; pop ecx ; pop ebp ; ret", "\x5e\x59\x5d\xc3", 4},
	{0, 0, "pop %esi ; pop %ecx ; pop %esp ; ret", "pop esi ; pop ecx ; pop esp ; ret", "\x5e\x59\x5c\xc3", 4},
	{0, 0, "pop %esi ; pop %edx ; pop %eax ; ret", "pop esi ; pop edx ; pop eax ; ret", "\x5e\x5a\x58\xc3", 4},
	{0, 0, "pop %esi ; pop %edx ; pop %ebx ; ret", "pop esi ; pop edx ; pop ebx ; ret", "\x5e\x5a\x5b\xc3", 4},
	{0, 0, "pop %esi ; pop %edx ; pop %ecx ; ret", "pop esi ; pop edx ; pop ecx ; ret", "\x5e\x5a\x59\xc3", 4},
	{0, 0, "pop %esi ; pop %edx ; pop %edx ; ret", "pop esi ; pop edx ; pop edx ; ret", "\x5e\x5a\x5a\xc3", 4},
	{0, 0, "pop %esi ; pop %edx ; pop %edi ; ret", "pop esi ; pop edx ; pop edi ; ret", "\x5e\x5a\x5f\xc3", 4},
	{0, 0, "pop %esi ; pop %edx ; pop %esi ; ret", "pop esi ; pop edx ; pop esi ; ret", "\x5e\x5a\x5e\xc3", 4},
	{0, 0, "pop %esi ; pop %edx ; pop %ebp ; ret", "pop esi ; pop edx ; pop ebp ; ret", "\x5e\x5a\x5d\xc3", 4},
	{0, 0, "pop %esi ; pop %edx ; pop %esp ; ret", "pop esi ; pop edx ; pop esp ; ret", "\x5e\x5a\x5c\xc3", 4},
	{0, 0, "pop %esi ; pop %edi ; pop %eax ; ret", "pop esi ; pop edi ; pop eax ; ret", "\x5e\x5f\x58\xc3", 4},
	{0, 0, "pop %esi ; pop %edi ; pop %ebx ; ret", "pop esi ; pop edi ; pop ebx ; ret", "\x5e\x5f\x5b\xc3", 4},
	{0, 0, "pop %esi ; pop %edi ; pop %ecx ; ret", "pop esi ; pop edi ; pop ecx ; ret", "\x5e\x5f\x59\xc3", 4},
	{0, 0, "pop %esi ; pop %edi ; pop %edx ; ret", "pop esi ; pop edi ; pop edx ; ret", "\x5e\x5f\x5a\xc3", 4},
	{0, 0, "pop %esi ; pop %edi ; pop %edi ; ret", "pop esi ; pop edi ; pop edi ; ret", "\x5e\x5f\x5f\xc3", 4},
	{0, 0, "pop %esi ; pop %edi ; pop %esi ; ret", "pop esi ; pop edi ; pop esi ; ret", "\x5e\x5f\x5e\xc3", 4},
	{0, 0, "pop %esi ; pop %edi ; pop %ebp ; ret", "pop esi ; pop edi ; pop ebp ; ret", "\x5e\x5f\x5d\xc3", 4},
	{0, 0, "pop %esi ; pop %edi ; pop %esp ; ret", "pop esi ; pop edi ; pop esp ; ret", "\x5e\x5f\x5c\xc3", 4},
	{0, 0, "pop %esi ; pop %esi ; pop %eax ; ret", "pop esi ; pop esi ; pop eax ; ret", "\x5e\x5e\x58\xc3", 4},
	{0, 0, "pop %esi ; pop %esi ; pop %ebx ; ret", "pop esi ; pop esi ; pop ebx ; ret", "\x5e\x5e\x5b\xc3", 4},
	{0, 0, "pop %esi ; pop %esi ; pop %ecx ; ret", "pop esi ; pop esi ; pop ecx ; ret", "\x5e\x5e\x59\xc3", 4},
	{0, 0, "pop %esi ; pop %esi ; pop %edx ; ret", "pop esi ; pop esi ; pop edx ; ret", "\x5e\x5e\x5a\xc3", 4},
	{0, 0, "pop %esi ; pop %esi ; pop %edi ; ret", "pop esi ; pop esi ; pop edi ; ret", "\x5e\x5e\x5f\xc3", 4},
	{0, 0, "pop %esi ; pop %esi ; pop %esi ; ret", "pop esi ; pop esi ; pop esi ; ret", "\x5e\x5e\x5e\xc3", 4},
	{0, 0, "pop %esi ; pop %esi ; pop %ebp ; ret", "pop esi ; pop esi ; pop ebp ; ret", "\x5e\x5e\x5d\xc3", 4},
	{0, 0, "pop %esi ; pop %esi ; pop %esp ; ret", "pop esi ; pop esi ; pop esp ; ret", "\x5e\x5e\x5c\xc3", 4},
	{0, 0, "pop %esi ; pop %ebp ; pop %eax ; ret", "pop esi ; pop ebp ; pop eax ; ret", "\x5e\x5d\x58\xc3", 4},
	{0, 0, "pop %esi ; pop %ebp ; pop %ebx ; ret", "pop esi ; pop ebp ; pop ebx ; ret", "\x5e\x5d\x5b\xc3", 4},
	{0, 0, "pop %esi ; pop %ebp ; pop %ecx ; ret", "pop esi ; pop ebp ; pop ecx ; ret", "\x5e\x5d\x59\xc3", 4},
	{0, 0, "pop %esi ; pop %ebp ; pop %edx ; ret", "pop esi ; pop ebp ; pop edx ; ret", "\x5e\x5d\x5a\xc3", 4},
	{0, 0, "pop %esi ; pop %ebp ; pop %edi ; ret", "pop esi ; pop ebp ; pop edi ; ret", "\x5e\x5d\x5f\xc3", 4},
	{0, 0, "pop %esi ; pop %ebp ; pop %esi ; ret", "pop esi ; pop ebp ; pop esi ; ret", "\x5e\x5d\x5e\xc3", 4},
	{0, 0, "pop %esi ; pop %ebp ; pop %ebp ; ret", "pop esi ; pop ebp ; pop ebp ; ret", "\x5e\x5d\x5d\xc3", 4},
	{0, 0, "pop %esi ; pop %ebp ; pop %esp ; ret", "pop esi ; pop ebp ; pop esp ; ret", "\x5e\x5d\x5c\xc3", 4},
	{0, 0, "pop %esi ; pop %esp ; pop %eax ; ret", "pop esi ; pop esp ; pop eax ; ret", "\x5e\x5c\x58\xc3", 4},
	{0, 0, "pop %esi ; pop %esp ; pop %ebx ; ret", "pop esi ; pop esp ; pop ebx ; ret", "\x5e\x5c\x5b\xc3", 4},
	{0, 0, "pop %esi ; pop %esp ; pop %ecx ; ret", "pop esi ; pop esp ; pop ecx ; ret", "\x5e\x5c\x59\xc3", 4},
	{0, 0, "pop %esi ; pop %esp ; pop %edx ; ret", "pop esi ; pop esp ; pop edx ; ret", "\x5e\x5c\x5a\xc3", 4},
	{0, 0, "pop %esi ; pop %esp ; pop %edi ; ret", "pop esi ; pop esp ; pop edi ; ret", "\x5e\x5c\x5f\xc3", 4},
	{0, 0, "pop %esi ; pop %esp ; pop %esi ; ret", "pop esi ; pop esp ; pop esi ; ret", "\x5e\x5c\x5e\xc3", 4},
	{0, 0, "pop %esi ; pop %esp ; pop %ebp ; ret", "pop esi ; pop esp ; pop ebp ; ret", "\x5e\x5c\x5d\xc3", 4},
	{0, 0, "pop %esi ; pop %esp ; pop %esp ; ret", "pop esi ; pop esp ; pop esp ; ret", "\x5e\x5c\x5c\xc3", 4},
	{0, 0, "pop %ebp ; pop %eax ; pop %eax ; ret", "pop ebp ; pop eax ; pop eax ; ret", "\x5d\x58\x58\xc3", 4},
	{0, 0, "pop %ebp ; pop %eax ; pop %ebx ; ret", "pop ebp ; pop eax ; pop ebx ; ret", "\x5d\x58\x5b\xc3", 4},
	{0, 0, "pop %ebp ; pop %eax ; pop %ecx ; ret", "pop ebp ; pop eax ; pop ecx ; ret", "\x5d\x58\x59\xc3", 4},
	{0, 0, "pop %ebp ; pop %eax ; pop %edx ; ret", "pop ebp ; pop eax ; pop edx ; ret", "\x5d\x58\x5a\xc3", 4},
	{0, 0, "pop %ebp ; pop %eax ; pop %edi ; ret", "pop ebp ; pop eax ; pop edi ; ret", "\x5d\x58\x5f\xc3", 4},
	{0, 0, "pop %ebp ; pop %eax ; pop %esi ; ret", "pop ebp ; pop eax ; pop esi ; ret", "\x5d\x58\x5e\xc3", 4},
	{0, 0, "pop %ebp ; pop %eax ; pop %ebp ; ret", "pop ebp ; pop eax ; pop ebp ; ret", "\x5d\x58\x5d\xc3", 4},
	{0, 0, "pop %ebp ; pop %eax ; pop %esp ; ret", "pop ebp ; pop eax ; pop esp ; ret", "\x5d\x58\x5c\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebx ; pop %eax ; ret", "pop ebp ; pop ebx ; pop eax ; ret", "\x5d\x5b\x58\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebx ; pop %ebx ; ret", "pop ebp ; pop ebx ; pop ebx ; ret", "\x5d\x5b\x5b\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebx ; pop %ecx ; ret", "pop ebp ; pop ebx ; pop ecx ; ret", "\x5d\x5b\x59\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebx ; pop %edx ; ret", "pop ebp ; pop ebx ; pop edx ; ret", "\x5d\x5b\x5a\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebx ; pop %edi ; ret", "pop ebp ; pop ebx ; pop edi ; ret", "\x5d\x5b\x5f\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebx ; pop %esi ; ret", "pop ebp ; pop ebx ; pop esi ; ret", "\x5d\x5b\x5e\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebx ; pop %ebp ; ret", "pop ebp ; pop ebx ; pop ebp ; ret", "\x5d\x5b\x5d\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebx ; pop %esp ; ret", "pop ebp ; pop ebx ; pop esp ; ret", "\x5d\x5b\x5c\xc3", 4},
	{0, 0, "pop %ebp ; pop %ecx ; pop %eax ; ret", "pop ebp ; pop ecx ; pop eax ; ret", "\x5d\x59\x58\xc3", 4},
	{0, 0, "pop %ebp ; pop %ecx ; pop %ebx ; ret", "pop ebp ; pop ecx ; pop ebx ; ret", "\x5d\x59\x5b\xc3", 4},
	{0, 0, "pop %ebp ; pop %ecx ; pop %ecx ; ret", "pop ebp ; pop ecx ; pop ecx ; ret", "\x5d\x59\x59\xc3", 4},
	{0, 0, "pop %ebp ; pop %ecx ; pop %edx ; ret", "pop ebp ; pop ecx ; pop edx ; ret", "\x5d\x59\x5a\xc3", 4},
	{0, 0, "pop %ebp ; pop %ecx ; pop %edi ; ret", "pop ebp ; pop ecx ; pop edi ; ret", "\x5d\x59\x5f\xc3", 4},
	{0, 0, "pop %ebp ; pop %ecx ; pop %esi ; ret", "pop ebp ; pop ecx ; pop esi ; ret", "\x5d\x59\x5e\xc3", 4},
	{0, 0, "pop %ebp ; pop %ecx ; pop %ebp ; ret", "pop ebp ; pop ecx ; pop ebp ; ret", "\x5d\x59\x5d\xc3", 4},
	{0, 0, "pop %ebp ; pop %ecx ; pop %esp ; ret", "pop ebp ; pop ecx ; pop esp ; ret", "\x5d\x59\x5c\xc3", 4},
	{0, 0, "pop %ebp ; pop %edx ; pop %eax ; ret", "pop ebp ; pop edx ; pop eax ; ret", "\x5d\x5a\x58\xc3", 4},
	{0, 0, "pop %ebp ; pop %edx ; pop %ebx ; ret", "pop ebp ; pop edx ; pop ebx ; ret", "\x5d\x5a\x5b\xc3", 4},
	{0, 0, "pop %ebp ; pop %edx ; pop %ecx ; ret", "pop ebp ; pop edx ; pop ecx ; ret", "\x5d\x5a\x59\xc3", 4},
	{0, 0, "pop %ebp ; pop %edx ; pop %edx ; ret", "pop ebp ; pop edx ; pop edx ; ret", "\x5d\x5a\x5a\xc3", 4},
	{0, 0, "pop %ebp ; pop %edx ; pop %edi ; ret", "pop ebp ; pop edx ; pop edi ; ret", "\x5d\x5a\x5f\xc3", 4},
	{0, 0, "pop %ebp ; pop %edx ; pop %esi ; ret", "pop ebp ; pop edx ; pop esi ; ret", "\x5d\x5a\x5e\xc3", 4},
	{0, 0, "pop %ebp ; pop %edx ; pop %ebp ; ret", "pop ebp ; pop edx ; pop ebp ; ret", "\x5d\x5a\x5d\xc3", 4},
	{0, 0, "pop %ebp ; pop %edx ; pop %esp ; ret", "pop ebp ; pop edx ; pop esp ; ret", "\x5d\x5a\x5c\xc3", 4},
	{0, 0, "pop %ebp ; pop %edi ; pop %eax ; ret", "pop ebp ; pop edi ; pop eax ; ret", "\x5d\x5f\x58\xc3", 4},
	{0, 0, "pop %ebp ; pop %edi ; pop %ebx ; ret", "pop ebp ; pop edi ; pop ebx ; ret", "\x5d\x5f\x5b\xc3", 4},
	{0, 0, "pop %ebp ; pop %edi ; pop %ecx ; ret", "pop ebp ; pop edi ; pop ecx ; ret", "\x5d\x5f\x59\xc3", 4},
	{0, 0, "pop %ebp ; pop %edi ; pop %edx ; ret", "pop ebp ; pop edi ; pop edx ; ret", "\x5d\x5f\x5a\xc3", 4},
	{0, 0, "pop %ebp ; pop %edi ; pop %edi ; ret", "pop ebp ; pop edi ; pop edi ; ret", "\x5d\x5f\x5f\xc3", 4},
	{0, 0, "pop %ebp ; pop %edi ; pop %esi ; ret", "pop ebp ; pop edi ; pop esi ; ret", "\x5d\x5f\x5e\xc3", 4},
	{0, 0, "pop %ebp ; pop %edi ; pop %ebp ; ret", "pop ebp ; pop edi ; pop ebp ; ret", "\x5d\x5f\x5d\xc3", 4},
	{0, 0, "pop %ebp ; pop %edi ; pop %esp ; ret", "pop ebp ; pop edi ; pop esp ; ret", "\x5d\x5f\x5c\xc3", 4},
	{0, 0, "pop %ebp ; pop %esi ; pop %eax ; ret", "pop ebp ; pop esi ; pop eax ; ret", "\x5d\x5e\x58\xc3", 4},
	{0, 0, "pop %ebp ; pop %esi ; pop %ebx ; ret", "pop ebp ; pop esi ; pop ebx ; ret", "\x5d\x5e\x5b\xc3", 4},
	{0, 0, "pop %ebp ; pop %esi ; pop %ecx ; ret", "pop ebp ; pop esi ; pop ecx ; ret", "\x5d\x5e\x59\xc3", 4},
	{0, 0, "pop %ebp ; pop %esi ; pop %edx ; ret", "pop ebp ; pop esi ; pop edx ; ret", "\x5d\x5e\x5a\xc3", 4},
	{0, 0, "pop %ebp ; pop %esi ; pop %edi ; ret", "pop ebp ; pop esi ; pop edi ; ret", "\x5d\x5e\x5f\xc3", 4},
	{0, 0, "pop %ebp ; pop %esi ; pop %esi ; ret", "pop ebp ; pop esi ; pop esi ; ret", "\x5d\x5e\x5e\xc3", 4},
	{0, 0, "pop %ebp ; pop %esi ; pop %ebp ; ret", "pop ebp ; pop esi ; pop ebp ; ret", "\x5d\x5e\x5d\xc3", 4},
	{0, 0, "pop %ebp ; pop %esi ; pop %esp ; ret", "pop ebp ; pop esi ; pop esp ; ret", "\x5d\x5e\x5c\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebp ; pop %eax ; ret", "pop ebp ; pop ebp ; pop eax ; ret", "\x5d\x5d\x58\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebp ; pop %ebx ; ret", "pop ebp ; pop ebp ; pop ebx ; ret", "\x5d\x5d\x5b\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebp ; pop %ecx ; ret", "pop ebp ; pop ebp ; pop ecx ; ret", "\x5d\x5d\x59\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebp ; pop %edx ; ret", "pop ebp ; pop ebp ; pop edx ; ret", "\x5d\x5d\x5a\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebp ; pop %edi ; ret", "pop ebp ; pop ebp ; pop edi ; ret", "\x5d\x5d\x5f\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebp ; pop %esi ; ret", "pop ebp ; pop ebp ; pop esi ; ret", "\x5d\x5d\x5e\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebp ; pop %ebp ; ret", "pop ebp ; pop ebp ; pop ebp ; ret", "\x5d\x5d\x5d\xc3", 4},
	{0, 0, "pop %ebp ; pop %ebp ; pop %esp ; ret", "pop ebp ; pop ebp ; pop esp ; ret", "\x5d\x5d\x5c\xc3", 4},
	{0, 0, "pop %ebp ; pop %esp ; pop %eax ; ret", "pop ebp ; pop esp ; pop eax ; ret", "\x5d\x5c\x58\xc3", 4},
	{0, 0, "pop %ebp ; pop %esp ; pop %ebx ; ret", "pop ebp ; pop esp ; pop ebx ; ret", "\x5d\x5c\x5b\xc3", 4},
	{0, 0, "pop %ebp ; pop %esp ; pop %ecx ; ret", "pop ebp ; pop esp ; pop ecx ; ret", "\x5d\x5c\x59\xc3", 4},
	{0, 0, "pop %ebp ; pop %esp ; pop %edx ; ret", "pop ebp ; pop esp ; pop edx ; ret", "\x5d\x5c\x5a\xc3", 4},
	{0, 0, "pop %ebp ; pop %esp ; pop %edi ; ret", "pop ebp ; pop esp ; pop edi ; ret", "\x5d\x5c\x5f\xc3", 4},
	{0, 0, "pop %ebp ; pop %esp ; pop %esi ; ret", "pop ebp ; pop esp ; pop esi ; ret", "\x5d\x5c\x5e\xc3", 4},
	{0, 0, "pop %ebp ; pop %esp ; pop %ebp ; ret", "pop ebp ; pop esp ; pop ebp ; ret", "\x5d\x5c\x5d\xc3", 4},
	{0, 0, "pop %ebp ; pop %esp ; pop %esp ; ret", "pop ebp ; pop esp ; pop esp ; ret", "\x5d\x5c\x5c\xc3", 4},
	{0, 0, "pop %esp ; pop %eax ; pop %eax ; ret", "pop esp ; pop eax ; pop eax ; ret", "\x5c\x58\x58\xc3", 4},
	{0, 0, "pop %esp ; pop %eax ; pop %ebx ; ret", "pop esp ; pop eax ; pop ebx ; ret", "\x5c\x58\x5b\xc3", 4},
	{0, 0, "pop %esp ; pop %eax ; pop %ecx ; ret", "pop esp ; pop eax ; pop ecx ; ret", "\x5c\x58\x59\xc3", 4},
	{0, 0, "pop %esp ; pop %eax ; pop %edx ; ret", "pop esp ; pop eax ; pop edx ; ret", "\x5c\x58\x5a\xc3", 4},
	{0, 0, "pop %esp ; pop %eax ; pop %edi ; ret", "pop esp ; pop eax ; pop edi ; ret", "\x5c\x58\x5f\xc3", 4},
	{0, 0, "pop %esp ; pop %eax ; pop %esi ; ret", "pop esp ; pop eax ; pop esi ; ret", "\x5c\x58\x5e\xc3", 4},
	{0, 0, "pop %esp ; pop %eax ; pop %ebp ; ret", "pop esp ; pop eax ; pop ebp ; ret", "\x5c\x58\x5d\xc3", 4},
	{0, 0, "pop %esp ; pop %eax ; pop %esp ; ret", "pop esp ; pop eax ; pop esp ; ret", "\x5c\x58\x5c\xc3", 4},
	{0, 0, "pop %esp ; pop %ebx ; pop %eax ; ret", "pop esp ; pop ebx ; pop eax ; ret", "\x5c\x5b\x58\xc3", 4},
	{0, 0, "pop %esp ; pop %ebx ; pop %ebx ; ret", "pop esp ; pop ebx ; pop ebx ; ret", "\x5c\x5b\x5b\xc3", 4},
	{0, 0, "pop %esp ; pop %ebx ; pop %ecx ; ret", "pop esp ; pop ebx ; pop ecx ; ret", "\x5c\x5b\x59\xc3", 4},
	{0, 0, "pop %esp ; pop %ebx ; pop %edx ; ret", "pop esp ; pop ebx ; pop edx ; ret", "\x5c\x5b\x5a\xc3", 4},
	{0, 0, "pop %esp ; pop %ebx ; pop %edi ; ret", "pop esp ; pop ebx ; pop edi ; ret", "\x5c\x5b\x5f\xc3", 4},
	{0, 0, "pop %esp ; pop %ebx ; pop %esi ; ret", "pop esp ; pop ebx ; pop esi ; ret", "\x5c\x5b\x5e\xc3", 4},
	{0, 0, "pop %esp ; pop %ebx ; pop %ebp ; ret", "pop esp ; pop ebx ; pop ebp ; ret", "\x5c\x5b\x5d\xc3", 4},
	{0, 0, "pop %esp ; pop %ebx ; pop %esp ; ret", "pop esp ; pop ebx ; pop esp ; ret", "\x5c\x5b\x5c\xc3", 4},
	{0, 0, "pop %esp ; pop %ecx ; pop %eax ; ret", "pop esp ; pop ecx ; pop eax ; ret", "\x5c\x59\x58\xc3", 4},
	{0, 0, "pop %esp ; pop %ecx ; pop %ebx ; ret", "pop esp ; pop ecx ; pop ebx ; ret", "\x5c\x59\x5b\xc3", 4},
	{0, 0, "pop %esp ; pop %ecx ; pop %ecx ; ret", "pop esp ; pop ecx ; pop ecx ; ret", "\x5c\x59\x59\xc3", 4},
	{0, 0, "pop %esp ; pop %ecx ; pop %edx ; ret", "pop esp ; pop ecx ; pop edx ; ret", "\x5c\x59\x5a\xc3", 4},
	{0, 0, "pop %esp ; pop %ecx ; pop %edi ; ret", "pop esp ; pop ecx ; pop edi ; ret", "\x5c\x59\x5f\xc3", 4},
	{0, 0, "pop %esp ; pop %ecx ; pop %esi ; ret", "pop esp ; pop ecx ; pop esi ; ret", "\x5c\x59\x5e\xc3", 4},
	{0, 0, "pop %esp ; pop %ecx ; pop %ebp ; ret", "pop esp ; pop ecx ; pop ebp ; ret", "\x5c\x59\x5d\xc3", 4},
	{0, 0, "pop %esp ; pop %ecx ; pop %esp ; ret", "pop esp ; pop ecx ; pop esp ; ret", "\x5c\x59\x5c\xc3", 4},
	{0, 0, "pop %esp ; pop %edx ; pop %eax ; ret", "pop esp ; pop edx ; pop eax ; ret", "\x5c\x5a\x58\xc3", 4},
	{0, 0, "pop %esp ; pop %edx ; pop %ebx ; ret", "pop esp ; pop edx ; pop ebx ; ret", "\x5c\x5a\x5b\xc3", 4},
	{0, 0, "pop %esp ; pop %edx ; pop %ecx ; ret", "pop esp ; pop edx ; pop ecx ; ret", "\x5c\x5a\x59\xc3", 4},
	{0, 0, "pop %esp ; pop %edx ; pop %edx ; ret", "pop esp ; pop edx ; pop edx ; ret", "\x5c\x5a\x5a\xc3", 4},
	{0, 0, "pop %esp ; pop %edx ; pop %edi ; ret", "pop esp ; pop edx ; pop edi ; ret", "\x5c\x5a\x5f\xc3", 4},
	{0, 0, "pop %esp ; pop %edx ; pop %esi ; ret", "pop esp ; pop edx ; pop esi ; ret", "\x5c\x5a\x5e\xc3", 4},
	{0, 0, "pop %esp ; pop %edx ; pop %ebp ; ret", "pop esp ; pop edx ; pop ebp ; ret", "\x5c\x5a\x5d\xc3", 4},
	{0, 0, "pop %esp ; pop %edx ; pop %esp ; ret", "pop esp ; pop edx ; pop esp ; ret", "\x5c\x5a\x5c\xc3", 4},
	{0, 0, "pop %esp ; pop %edi ; pop %eax ; ret", "pop esp ; pop edi ; pop eax ; ret", "\x5c\x5f\x58\xc3", 4},
	{0, 0, "pop %esp ; pop %edi ; pop %ebx ; ret", "pop esp ; pop edi ; pop ebx ; ret", "\x5c\x5f\x5b\xc3", 4},
	{0, 0, "pop %esp ; pop %edi ; pop %ecx ; ret", "pop esp ; pop edi ; pop ecx ; ret", "\x5c\x5f\x59\xc3", 4},
	{0, 0, "pop %esp ; pop %edi ; pop %edx ; ret", "pop esp ; pop edi ; pop edx ; ret", "\x5c\x5f\x5a\xc3", 4},
	{0, 0, "pop %esp ; pop %edi ; pop %edi ; ret", "pop esp ; pop edi ; pop edi ; ret", "\x5c\x5f\x5f\xc3", 4},
	{0, 0, "pop %esp ; pop %edi ; pop %esi ; ret", "pop esp ; pop edi ; pop esi ; ret", "\x5c\x5f\x5e\xc3", 4},
	{0, 0, "pop %esp ; pop %edi ; pop %ebp ; ret", "pop esp ; pop edi ; pop ebp ; ret", "\x5c\x5f\x5d\xc3", 4},
	{0, 0, "pop %esp ; pop %edi ; pop %esp ; ret", "pop esp ; pop edi ; pop esp ; ret", "\x5c\x5f\x5c\xc3", 4},
	{0, 0, "pop %esp ; pop %esi ; pop %eax ; ret", "pop esp ; pop esi ; pop eax ; ret", "\x5c\x5e\x58\xc3", 4},
	{0, 0, "pop %esp ; pop %esi ; pop %ebx ; ret", "pop esp ; pop esi ; pop ebx ; ret", "\x5c\x5e\x5b\xc3", 4},
	{0, 0, "pop %esp ; pop %esi ; pop %ecx ; ret", "pop esp ; pop esi ; pop ecx ; ret", "\x5c\x5e\x59\xc3", 4},
	{0, 0, "pop %esp ; pop %esi ; pop %edx ; ret", "pop esp ; pop esi ; pop edx ; ret", "\x5c\x5e\x5a\xc3", 4},
	{0, 0, "pop %esp ; pop %esi ; pop %edi ; ret", "pop esp ; pop esi ; pop edi ; ret", "\x5c\x5e\x5f\xc3", 4},
	{0, 0, "pop %esp ; pop %esi ; pop %esi ; ret", "pop esp ; pop esi ; pop esi ; ret", "\x5c\x5e\x5e\xc3", 4},
	{0, 0, "pop %esp ; pop %esi ; pop %ebp ; ret", "pop esp ; pop esi ; pop ebp ; ret", "\x5c\x5e\x5d\xc3", 4},
	{0, 0, "pop %esp ; pop %esi ; pop %esp ; ret", "pop esp ; pop esi ; pop esp ; ret", "\x5c\x5e\x5c\xc3", 4},
	{0, 0, "pop %esp ; pop %ebp ; pop %eax ; ret", "pop esp ; pop ebp ; pop eax ; ret", "\x5c\x5d\x58\xc3", 4},
	{0, 0, "pop %esp ; pop %ebp ; pop %ebx ; ret", "pop esp ; pop ebp ; pop ebx ; ret", "\x5c\x5d\x5b\xc3", 4},
	{0, 0, "pop %esp ; pop %ebp ; pop %ecx ; ret", "pop esp ; pop ebp ; pop ecx ; ret", "\x5c\x5d\x59\xc3", 4},
	{0, 0, "pop %esp ; pop %ebp ; pop %edx ; ret", "pop esp ; pop ebp ; pop edx ; ret", "\x5c\x5d\x5a\xc3", 4},
	{0, 0, "pop %esp ; pop %ebp ; pop %edi ; ret", "pop esp ; pop ebp ; pop edi ; ret", "\x5c\x5d\x5f\xc3", 4},
	{0, 0, "pop %esp ; pop %ebp ; pop %esi ; ret", "pop esp ; pop ebp ; pop esi ; ret", "\x5c\x5d\x5e\xc3", 4},
	{0, 0, "pop %esp ; pop %ebp ; pop %ebp ; ret", "pop esp ; pop ebp ; pop ebp ; ret", "\x5c\x5d\x5d\xc3", 4},
	{0, 0, "pop %esp ; pop %ebp ; pop %esp ; ret", "pop esp ; pop ebp ; pop esp ; ret", "\x5c\x5d\x5c\xc3", 4},
	{0, 0, "pop %esp ; pop %esp ; pop %eax ; ret", "pop esp ; pop esp ; pop eax ; ret", "\x5c\x5c\x58\xc3", 4},
	{0, 0, "pop %esp ; pop %esp ; pop %ebx ; ret", "pop esp ; pop esp ; pop ebx ; ret", "\x5c\x5c\x5b\xc3", 4},
	{0, 0, "pop %esp ; pop %esp ; pop %ecx ; ret", "pop esp ; pop esp ; pop ecx ; ret", "\x5c\x5c\x59\xc3", 4},
	{0, 0, "pop %esp ; pop %esp ; pop %edx ; ret", "pop esp ; pop esp ; pop edx ; ret", "\x5c\x5c\x5a\xc3", 4},
	{0, 0, "pop %esp ; pop %esp ; pop %edi ; ret", "pop esp ; pop esp ; pop edi ; ret", "\x5c\x5c\x5f\xc3", 4},
	{0, 0, "pop %esp ; pop %esp ; pop %esi ; ret", "pop esp ; pop esp ; pop esi ; ret", "\x5c\x5c\x5e\xc3", 4},
	{0, 0, "pop %esp ; pop %esp ; pop %ebp ; ret", "pop esp ; pop esp ; pop ebp ; ret", "\x5c\x5c\x5d\xc3", 4},
	{0, 0, "pop %esp ; pop %esp ; pop %esp ; ret", "pop esp ; pop esp ; pop esp ; ret", "\x5c\x5c\x5c\xc3", 4},
	{0, 0, "pop %eax ; ret", "pop eax ; ret", "\x58\xc3", 2},
	{0, 0, "pop %ebx ; ret", "pop ebx ; ret", "\x5b\xc3", 2},
	{0, 0, "pop %ecx ; ret", "pop ecx ; ret", "\x59\xc3", 2},
	{0, 0, "pop %edx ; ret", "pop edx ; ret", "\x5a\xc3", 2},
	{0, 0, "pop %edi ; ret", "pop edi ; ret", "\x5f\xc3", 2},
	{0, 0, "pop %esi ; ret", "pop esi ; ret", "\x5e\xc3", 2},
	{0, 0, "pop %ebp ; ret", "pop ebp ; ret", "\x5d\xc3", 2},
	{0, 0, "pop %esp ; ret", "pop esp ; ret", "\x5c\xc3", 2},
	{0, 0, "push %eax ; ret", "push eax ; ret", "\x50\xc3", 2},
	{0, 0, "push %ebx ; ret", "push ebx ; ret", "\x53\xc3", 2},
	{0, 0, "push %ecx ; ret", "push ecx ; ret", "\x51\xc3", 2},
	{0, 0, "push %edx ; ret", "push edx ; ret", "\x52\xc3", 2},
	{0, 0, "push %edi ; ret", "push edi ; ret", "\x57\xc3", 2},
	{0, 0, "push %esi ; ret", "push esi ; ret", "\x56\xc3", 2},
	{0, 0, "push %ebp ; ret", "push ebp ; ret", "\x55\xc3", 2},
	{0, 0, "push %esp ; ret", "push esp ; ret", "\x54\xc3", 2},
	{0, 0, "inc %eax ; ret", "inc eax ; ret", "\x40\xc3", 2},
	{0, 0, "inc %ebx ; ret", "inc ebx ; ret", "\x43\xc3", 2},
	{0, 0, "inc %ecx ; ret", "inc ecx ; ret", "\x41\xc3", 2},
	{0, 0, "inc %edx ; ret", "inc edx ; ret", "\x42\xc3", 2},
	{0, 0, "inc %edi ; ret", "inc edi ; ret", "\x47\xc3", 2},
	{0, 0, "inc %esi ; ret", "inc esi ; ret", "\x46\xc3", 2},
	{0, 0, "inc %ebp ; ret", "inc ebp ; ret", "\x45\xc3", 2},
	{0, 0, "inc %esp ; ret", "inc esp ; ret", "\x44\xc3", 2},
	{0, 0, "dec %eax ; ret", "dec eax ; ret", "\x48\xc3", 2},
	{0, 0, "dec %ebx ; ret", "dec ebx ; ret", "\x4b\xc3", 2},
	{0, 0, "dec %ecx ; ret", "dec ecx ; ret", "\x49\xc3", 2},
	{0, 0, "dec %edx ; ret", "dec edx ; ret", "\x4a\xc3", 2},
	{0, 0, "dec %edi ; ret", "dec edi ; ret", "\x4f\xc3", 2},
	{0, 0, "dec %esi ; ret", "dec esi ; ret", "\x4e\xc3", 2},
	{0, 0, "dec %ebp ; ret", "dec ebp ; ret", "\x4d\xc3", 2},
	{0, 0, "dec %esp ; ret", "dec esp ; ret", "\x4c\xc3", 2},
	{0, 0, "div %eax ; ret", "div eax ; ret", "\xf7\xf0\xc3", 3},
	{0, 0, "div %ebx ; ret", "div ebx ; ret", "\xf7\xf3\xc3", 3},
	{0, 0, "div %ecx ; ret", "div ecx ; ret", "\xf7\xf1\xc3", 3},
	{0, 0, "div %edx ; ret", "div edx ; ret", "\xf7\xf2\xc3", 3},
	{0, 0, "div %edi ; ret", "div edi ; ret", "\xf7\xf7\xc3", 3},
	{0, 0, "div %esi ; ret", "div esi ; ret", "\xf7\xf6\xc3", 3},
	{0, 0, "div %ebp ; ret", "div ebp ; ret", "\xf7\xf5\xc3", 3},
	{0, 0, "div %esp ; ret", "div esp ; ret", "\xf7\xf4\xc3", 3},
	{0, 0, "mul %eax ; ret", "mul eax ; ret", "\xf7\xe0\xc3", 3},
	{0, 0, "mul %ebx ; ret", "mul ebx ; ret", "\xf7\xe3\xc3", 3},
	{0, 0, "mul %ecx ; ret", "mul ecx ; ret", "\xf7\xe1\xc3", 3},
	{0, 0, "mul %edx ; ret", "mul edx ; ret", "\xf7\xe2\xc3", 3},
	{0, 0, "mul %edi ; ret", "mul edi ; ret", "\xf7\xe7\xc3", 3},
	{0, 0, "mul %esi ; ret", "mul esi ; ret", "\xf7\xe6\xc3", 3},
	{0, 0, "mul %ebp ; ret", "mul ebp ; ret", "\xf7\xe5\xc3", 3},
	{0, 0, "mul %esp ; ret", "mul esp ; ret", "\xf7\xe4\xc3", 3},
	{0, 0, "neg %eax ; ret", "neg eax ; ret", "\xf7\xd8\xc3", 3},
	{0, 0, "neg %ebx ; ret", "neg ebx ; ret", "\xf7\xdb\xc3", 3},
	{0, 0, "neg %ecx ; ret", "neg ecx ; ret", "\xf7\xd9\xc3", 3},
	{0, 0, "neg %edx ; ret", "neg edx ; ret", "\xf7\xda\xc3", 3},
	{0, 0, "neg %edi ; ret", "neg edi ; ret", "\xf7\xdf\xc3", 3},
	{0, 0, "neg %esi ; ret", "neg esi ; ret", "\xf7\xde\xc3", 3},
	{0, 0, "neg %ebp ; ret", "neg ebp ; ret", "\xf7\xdd\xc3", 3},
	{0, 0, "neg %esp ; ret", "neg esp ; ret", "\xf7\xdc\xc3", 3},
	{0, 0, "not %eax ; ret", "not eax ; ret", "\xf7\xd0\xc3", 3},
	{0, 0, "not %ebx ; ret", "not ebx ; ret", "\xf7\xd3\xc3", 3},
	{0, 0, "not %ecx ; ret", "not ecx ; ret", "\xf7\xd1\xc3", 3},
	{0, 0, "not %edx ; ret", "not edx ; ret", "\xf7\xd2\xc3", 3},
	{0, 0, "not %edi ; ret", "not edi ; ret", "\xf7\xd7\xc3", 3},
	{0, 0, "not %esi ; ret", "not esi ; ret", "\xf7\xd6\xc3", 3},
	{0, 0, "not %ebp ; ret", "not ebp ; ret", "\xf7\xd5\xc3", 3},
	{0, 0, "not %esp ; ret", "not esp ; ret", "\xf7\xd4\xc3", 3},
	{0, 0, "shr %eax ; ret", "shr eax,1 ; ret", "\xd1\xe8\xc3", 3},
	{0, 0, "shr %ebx ; ret", "shr ebx,1 ; ret", "\xd1\xeb\xc3", 3},
	{0, 0, "shr %ecx ; ret", "shr ecx,1 ; ret", "\xd1\xe9\xc3", 3},
	{0, 0, "shr %edx ; ret", "shr edx,1 ; ret", "\xd1\xea\xc3", 3},
	{0, 0, "shr %edi ; ret", "shr edi,1 ; ret", "\xd1\xef\xc3", 3},
	{0, 0, "shr %esi ; ret", "shr esi,1 ; ret", "\xd1\xee\xc3", 3},
	{0, 0, "shr %ebp ; ret", "shr ebp,1 ; ret", "\xd1\xed\xc3", 3},
	{0, 0, "shr %esp ; ret", "shr esp,1 ; ret", "\xd1\xec\xc3", 3},
	{0, 0, "shl %eax ; ret", "shl eax,1 ; ret", "\xd1\xe0\xc3", 3},
	{0, 0, "shl %ebx ; ret", "shl ebx,1 ; ret", "\xd1\xe3\xc3", 3},
	{0, 0, "shl %ecx ; ret", "shl ecx,1 ; ret", "\xd1\xe1\xc3", 3},
	{0, 0, "shl %edx ; ret", "shl edx,1 ; ret", "\xd1\xe2\xc3", 3},
	{0, 0, "shl %edi ; ret", "shl edi,1 ; ret", "\xd1\xe7\xc3", 3},
	{0, 0, "shl %esi ; ret", "shl esi,1 ; ret", "\xd1\xe6\xc3", 3},
	{0, 0, "shl %ebp ; ret", "shl ebp,1 ; ret", "\xd1\xe5\xc3", 3},
	{0, 0, "shl %esp ; ret", "shl esp,1 ; ret", "\xd1\xe4\xc3", 3},
	{0, 0, "ror %eax ; ret", "ror eax,1 ; ret", "\xd1\xc8\xc3", 3},
	{0, 0, "ror %ebx ; ret", "ror ebx,1 ; ret", "\xd1\xcb\xc3", 3},
	{0, 0, "ror %ecx ; ret", "ror ecx,1 ; ret", "\xd1\xc9\xc3", 3},
	{0, 0, "ror %edx ; ret", "ror edx,1 ; ret", "\xd1\xca\xc3", 3},
	{0, 0, "ror %edi ; ret", "ror edi,1 ; ret", "\xd1\xcf\xc3", 3},
	{0, 0, "ror %esi ; ret", "ror esi,1 ; ret", "\xd1\xce\xc3", 3},
	{0, 0, "ror %ebp ; ret", "ror ebp,1 ; ret", "\xd1\xcd\xc3", 3},
	{0, 0, "ror %esp ; ret", "ror esp,1 ; ret", "\xd1\xcc\xc3", 3},
	{0, 0, "rol %eax ; ret", "rol eax,1 ; ret", "\xd1\xc0\xc3", 3},
	{0, 0, "rol %ebx ; ret", "rol ebx,1 ; ret", "\xd1\xc3\xc3", 3},
	{0, 0, "rol %ecx ; ret", "rol ecx,1 ; ret", "\xd1\xc1\xc3", 3},
	{0, 0, "rol %edx ; ret", "rol edx,1 ; ret", "\xd1\xc2\xc3", 3},
	{0, 0, "rol %edi ; ret", "rol edi,1 ; ret", "\xd1\xc7\xc3", 3},
	{0, 0, "rol %esi ; ret", "rol esi,1 ; ret", "\xd1\xc6\xc3", 3},
	{0, 0, "rol %ebp ; ret", "rol ebp,1 ; ret", "\xd1\xc5\xc3", 3},
	{0, 0, "rol %esp ; ret", "rol esp,1 ; ret", "\xd1\xc4\xc3", 3},
	{0, 0, "bswap %eax ; ret", "bswap eax ; ret", "\x0f\xc8\xc3", 3},
	{0, 0, "bswap %ebx ; ret", "bswap ebx ; ret", "\x0f\xcb\xc3", 3},
	{0, 0, "bswap %ecx ; ret", "bswap ecx ; ret", "\x0f\xc9\xc3", 3},
	{0, 0, "bswap %edx ; ret", "bswap edx ; ret", "\x0f\xca\xc3", 3},
	{0, 0, "bswap %edi ; ret", "bswap edi ; ret", "\x0f\xcf\xc3", 3},
	{0, 0, "bswap %esi ; ret", "bswap esi ; ret", "\x0f\xce\xc3", 3},
	{0, 0, "bswap %ebp ; ret", "bswap ebp ; ret", "\x0f\xcd\xc3", 3},
	{0, 0, "bswap %esp ; ret", "bswap esp ; ret", "\x0f\xcc\xc3", 3},
	{0, 0, "xor %eax,%eax ; ret", "xor eax,eax ; ret", "\x31\xc0\xc3", 3},
	{0, 0, "xor %eax,%ebx ; ret", "xor ebx,eax ; ret", "\x31\xc3\xc3", 3},
	{0, 0, "xor %eax,%ecx ; ret", "xor ecx,eax ; ret", "\x31\xc1\xc3", 3},
	{0, 0, "xor %eax,%edx ; ret", "xor edx,eax ; ret", "\x31\xc2\xc3", 3},
	{0, 0, "xor %eax,%edi ; ret", "xor edi,eax ; ret", "\x31\xc7\xc3", 3},
	{0, 0, "xor %eax,%esi ; ret", "xor esi,eax ; ret", "\x31\xc6\xc3", 3},
	{0, 0, "xor %eax,%ebp ; ret", "xor ebp,eax ; ret", "\x31\xc5\xc3", 3},
	{0, 0, "xor %eax,%esp ; ret", "xor esp,eax ; ret", "\x31\xc4\xc3", 3},
	{0, 0, "xor %ebx,%eax ; ret", "xor eax,ebx ; ret", "\x31\xd8\xc3", 3},
	{0, 0, "xor %ebx,%ebx ; ret", "xor ebx,ebx ; ret", "\x31\xdb\xc3", 3},
	{0, 0, "xor %ebx,%ecx ; ret", "xor ecx,ebx ; ret", "\x31\xd9\xc3", 3},
	{0, 0, "xor %ebx,%edx ; ret", "xor edx,ebx ; ret", "\x31\xda\xc3", 3},
	{0, 0, "xor %ebx,%edi ; ret", "xor edi,ebx ; ret", "\x31\xdf\xc3", 3},
	{0, 0, "xor %ebx,%esi ; ret", "xor esi,ebx ; ret", "\x31\xde\xc3", 3},
	{0, 0, "xor %ebx,%ebp ; ret", "xor ebp,ebx ; ret", "\x31\xdd\xc3", 3},
	{0, 0, "xor %ebx,%esp ; ret", "xor esp,ebx ; ret", "\x31\xdc\xc3", 3},
	{0, 0, "xor %ecx,%eax ; ret", "xor eax,ecx ; ret", "\x31\xc8\xc3", 3},
	{0, 0, "xor %ecx,%ebx ; ret", "xor ebx,ecx ; ret", "\x31\xcb\xc3", 3},
	{0, 0, "xor %ecx,%ecx ; ret", "xor ecx,ecx ; ret", "\x31\xc9\xc3", 3},
	{0, 0, "xor %ecx,%edx ; ret", "xor edx,ecx ; ret", "\x31\xca\xc3", 3},
	{0, 0, "xor %ecx,%edi ; ret", "xor edi,ecx ; ret", "\x31\xcf\xc3", 3},
	{0, 0, "xor %ecx,%esi ; ret", "xor esi,ecx ; ret", "\x31\xce\xc3", 3},
	{0, 0, "xor %ecx,%ebp ; ret", "xor ebp,ecx ; ret", "\x31\xcd\xc3", 3},
	{0, 0, "xor %ecx,%esp ; ret", "xor esp,ecx ; ret", "\x31\xcc\xc3", 3},
	{0, 0, "xor %edx,%eax ; ret", "xor eax,edx ; ret", "\x31\xd0\xc3", 3},
	{0, 0, "xor %edx,%ebx ; ret", "xor ebx,edx ; ret", "\x31\xd3\xc3", 3},
	{0, 0, "xor %edx,%ecx ; ret", "xor ecx,edx ; ret", "\x31\xd1\xc3", 3},
	{0, 0, "xor %edx,%edx ; ret", "xor edx,edx ; ret", "\x31\xd2\xc3", 3},
	{0, 0, "xor %edx,%edi ; ret", "xor edi,edx ; ret", "\x31\xd7\xc3", 3},
	{0, 0, "xor %edx,%esi ; ret", "xor esi,edx ; ret", "\x31\xd6\xc3", 3},
	{0, 0, "xor %edx,%ebp ; ret", "xor ebp,edx ; ret", "\x31\xd5\xc3", 3},
	{0, 0, "xor %edx,%esp ; ret", "xor esp,edx ; ret", "\x31\xd4\xc3", 3},
	{0, 0, "xor %edi,%eax ; ret", "xor eax,edi ; ret", "\x31\xf8\xc3", 3},
	{0, 0, "xor %edi,%ebx ; ret", "xor ebx,edi ; ret", "\x31\xfb\xc3", 3},
	{0, 0, "xor %edi,%ecx ; ret", "xor ecx,edi ; ret", "\x31\xf9\xc3", 3},
	{0, 0, "xor %edi,%edx ; ret", "xor edx,edi ; ret", "\x31\xfa\xc3", 3},
	{0, 0, "xor %edi,%edi ; ret", "xor edi,edi ; ret", "\x31\xff\xc3", 3},
	{0, 0, "xor %edi,%esi ; ret", "xor esi,edi ; ret", "\x31\xfe\xc3", 3},
	{0, 0, "xor %edi,%ebp ; ret", "xor ebp,edi ; ret", "\x31\xfd\xc3", 3},
	{0, 0, "xor %edi,%esp ; ret", "xor esp,edi ; ret", "\x31\xfc\xc3", 3},
	{0, 0, "xor %esi,%eax ; ret", "xor eax,esi ; ret", "\x31\xf0\xc3", 3},
	{0, 0, "xor %esi,%ebx ; ret", "xor ebx,esi ; ret", "\x31\xf3\xc3", 3},
	{0, 0, "xor %esi,%ecx ; ret", "xor ecx,esi ; ret", "\x31\xf1\xc3", 3},
	{0, 0, "xor %esi,%edx ; ret", "xor edx,esi ; ret", "\x31\xf2\xc3", 3},
	{0, 0, "xor %esi,%edi ; ret", "xor edi,esi ; ret", "\x31\xf7\xc3", 3},
	{0, 0, "xor %esi,%esi ; ret", "xor esi,esi ; ret", "\x31\xf6\xc3", 3},
	{0, 0, "xor %esi,%ebp ; ret", "xor ebp,esi ; ret", "\x31\xf5\xc3", 3},
	{0, 0, "xor %esi,%esp ; ret", "xor esp,esi ; ret", "\x31\xf4\xc3", 3},
	{0, 0, "xor %ebp,%eax ; ret", "xor eax,ebp ; ret", "\x31\xe8\xc3", 3},
	{0, 0, "xor %ebp,%ebx ; ret", "xor ebx,ebp ; ret", "\x31\xeb\xc3", 3},
	{0, 0, "xor %ebp,%ecx ; ret", "xor ecx,ebp ; ret", "\x31\xe9\xc3", 3},
	{0, 0, "xor %ebp,%edx ; ret", "xor edx,ebp ; ret", "\x31\xea\xc3", 3},
	{0, 0, "xor %ebp,%edi ; ret", "xor edi,ebp ; ret", "\x31\xef\xc3", 3},
	{0, 0, "xor %ebp,%esi ; ret", "xor esi,ebp ; ret", "\x31\xee\xc3", 3},
	{0, 0, "xor %ebp,%ebp ; ret", "xor ebp,ebp ; ret", "\x31\xed\xc3", 3},
	{0, 0, "xor %ebp,%esp ; ret", "xor esp,ebp ; ret", "\x31\xec\xc3", 3},
	{0, 0, "xor %esp,%eax ; ret", "xor eax,esp ; ret", "\x31\xe0\xc3", 3},
	{0, 0, "xor %esp,%ebx ; ret", "xor ebx,esp ; ret", "\x31\xe3\xc3", 3},
	{0, 0, "xor %esp,%ecx ; ret", "xor ecx,esp ; ret", "\x31\xe1\xc3", 3},
	{0, 0, "xor %esp,%edx ; ret", "xor edx,esp ; ret", "\x31\xe2\xc3", 3},
	{0, 0, "xor %esp,%edi ; ret", "xor edi,esp ; ret", "\x31\xe7\xc3", 3},
	{0, 0, "xor %esp,%esi ; ret", "xor esi,esp ; ret", "\x31\xe6\xc3", 3},
	{0, 0, "xor %esp,%ebp ; ret", "xor ebp,esp ; ret", "\x31\xe5\xc3", 3},
	{0, 0, "xor %esp,%esp ; ret", "xor esp,esp ; ret", "\x31\xe4\xc3", 3},
	{0, 0, "nop ; ret", "nop ; ret", "\x90\xc3", 2},
	{0, 0, "xchg %eax,%ebx ; ret", "xchg ebx,eax ; ret", "\x93\xc3", 2},
	{0, 0, "xchg %eax,%ecx ; ret", "xchg ecx,eax ; ret", "\x91\xc3", 2},
	{0, 0, "xchg %eax,%edx ; ret", "xchg edx,eax ; ret", "\x92\xc3", 2},
	{0, 0, "xchg %eax,%edi ; ret", "xchg edi,eax ; ret", "\x97\xc3", 2},
	{0, 0, "xchg %eax,%esi ; ret", "xchg esi,eax ; ret", "\x96\xc3", 2},
	{0, 0, "xchg %eax,%ebp ; ret", "xchg ebp,eax ; ret", "\x95\xc3", 2},
	{0, 0, "xchg %eax,%esp ; ret", "xchg esp,eax ; ret", "\x94\xc3", 2},
	{0, 0, "xchg %eax,%ebx ; ret", "xchg ebx,eax ; ret", "\x93\xc3", 2},
	{0, 0, "xchg %ebx,%ebx ; ret", "xchg ebx,ebx ; ret", "\x87\xdb\xc3", 3},
	{0, 0, "xchg %ebx,%ecx ; ret", "xchg ecx,ebx ; ret", "\x87\xd9\xc3", 3},
	{0, 0, "xchg %ebx,%edx ; ret", "xchg edx,ebx ; ret", "\x87\xda\xc3", 3},
	{0, 0, "xchg %ebx,%edi ; ret", "xchg edi,ebx ; ret", "\x87\xdf\xc3", 3},
	{0, 0, "xchg %ebx,%esi ; ret", "xchg esi,ebx ; ret", "\x87\xde\xc3", 3},
	{0, 0, "xchg %ebx,%ebp ; ret", "xchg ebp,ebx ; ret", "\x87\xdd\xc3", 3},
	{0, 0, "xchg %ebx,%esp ; ret", "xchg esp,ebx ; ret", "\x87\xdc\xc3", 3},
	{0, 0, "xchg %eax,%ecx ; ret", "xchg ecx,eax ; ret", "\x91\xc3", 2},
	{0, 0, "xchg %ecx,%ebx ; ret", "xchg ebx,ecx ; ret", "\x87\xcb\xc3", 3},
	{0, 0, "xchg %ecx,%ecx ; ret", "xchg ecx,ecx ; ret", "\x87\xc9\xc3", 3},
	{0, 0, "xchg %ecx,%edx ; ret", "xchg edx,ecx ; ret", "\x87\xca\xc3", 3},
	{0, 0, "xchg %ecx,%edi ; ret", "xchg edi,ecx ; ret", "\x87\xcf\xc3", 3},
	{0, 0, "xchg %ecx,%esi ; ret", "xchg esi,ecx ; ret", "\x87\xce\xc3", 3},
	{0, 0, "xchg %ecx,%ebp ; ret", "xchg ebp,ecx ; ret", "\x87\xcd\xc3", 3},
	{0, 0, "xchg %ecx,%esp ; ret", "xchg esp,ecx ; ret", "\x87\xcc\xc3", 3},
	{0, 0, "xchg %eax,%edx ; ret", "xchg edx,eax ; ret", "\x92\xc3", 2},
	{0, 0, "xchg %edx,%ebx ; ret", "xchg ebx,edx ; ret", "\x87\xd3\xc3", 3},
	{0, 0, "xchg %edx,%ecx ; ret", "xchg ecx,edx ; ret", "\x87\xd1\xc3", 3},
	{0, 0, "xchg %edx,%edx ; ret", "xchg edx,edx ; ret", "\x87\xd2\xc3", 3},
	{0, 0, "xchg %edx,%edi ; ret", "xchg edi,edx ; ret", "\x87\xd7\xc3", 3},
	{0, 0, "xchg %edx,%esi ; ret", "xchg esi,edx ; ret", "\x87\xd6\xc3", 3},
	{0, 0, "xchg %edx,%ebp ; ret", "xchg ebp,edx ; ret", "\x87\xd5\xc3", 3},
	{0, 0, "xchg %edx,%esp ; ret", "xchg esp,edx ; ret", "\x87\xd4\xc3", 3},
	{0, 0, "xchg %eax,%edi ; ret", "xchg edi,eax ; ret", "\x97\xc3", 2},
	{0, 0, "xchg %edi,%ebx ; ret", "xchg ebx,edi ; ret", "\x87\xfb\xc3", 3},
	{0, 0, "xchg %edi,%ecx ; ret", "xchg ecx,edi ; ret", "\x87\xf9\xc3", 3},
	{0, 0, "xchg %edi,%edx ; ret", "xchg edx,edi ; ret", "\x87\xfa\xc3", 3},
	{0, 0, "xchg %edi,%edi ; ret", "xchg edi,edi ; ret", "\x87\xff\xc3", 3},
	{0, 0, "xchg %edi,%esi ; ret", "xchg esi,edi ; ret", "\x87\xfe\xc3", 3},
	{0, 0, "xchg %edi,%ebp ; ret", "xchg ebp,edi ; ret", "\x87\xfd\xc3", 3},
	{0, 0, "xchg %edi,%esp ; ret", "xchg esp,edi ; ret", "\x87\xfc\xc3", 3},
	{0, 0, "xchg %eax,%esi ; ret", "xchg esi,eax ; ret", "\x96\xc3", 2},
	{0, 0, "xchg %esi,%ebx ; ret", "xchg ebx,esi ; ret", "\x87\xf3\xc3", 3},
	{0, 0, "xchg %esi,%ecx ; ret", "xchg ecx,esi ; ret", "\x87\xf1\xc3", 3},
	{0, 0, "xchg %esi,%edx ; ret", "xchg edx,esi ; ret", "\x87\xf2\xc3", 3},
	{0, 0, "xchg %esi,%edi ; ret", "xchg edi,esi ; ret", "\x87\xf7\xc3", 3},
	{0, 0, "xchg %esi,%esi ; ret", "xchg esi,esi ; ret", "\x87\xf6\xc3", 3},
	{0, 0, "xchg %esi,%ebp ; ret", "xchg ebp,esi ; ret", "\x87\xf5\xc3", 3},
	{0, 0, "xchg %esi,%esp ; ret", "xchg esp,esi ; ret", "\x87\xf4\xc3", 3},
	{0, 0, "xchg %eax,%ebp ; ret", "xchg ebp,eax ; ret", "\x95\xc3", 2},
	{0, 0, "xchg %ebp,%ebx ; ret", "xchg ebx,ebp ; ret", "\x87\xeb\xc3", 3},
	{0, 0, "xchg %ebp,%ecx ; ret", "xchg ecx,ebp ; ret", "\x87\xe9\xc3", 3},
	{0, 0, "xchg %ebp,%edx ; ret", "xchg edx,ebp ; ret", "\x87\xea\xc3", 3},
	{0, 0, "xchg %ebp,%edi ; ret", "xchg edi,ebp ; ret", "\x87\xef\xc3", 3},
	{0, 0, "xchg %ebp,%esi ; ret", "xchg esi,ebp ; ret", "\x87\xee\xc3", 3},
	{0, 0, "xchg %ebp,%ebp ; ret", "xchg ebp,ebp ; ret", "\x87\xed\xc3", 3},
	{0, 0, "xchg %ebp,%esp ; ret", "xchg esp,ebp ; ret", "\x87\xec\xc3", 3},
	{0, 0, "xchg %eax,%esp ; ret", "xchg esp,eax ; ret", "\x94\xc3", 2},
	{0, 0, "xchg %esp,%ebx ; ret", "xchg ebx,esp ; ret", "\x87\xe3\xc3", 3},
	{0, 0, "xchg %esp,%ecx ; ret", "xchg ecx,esp ; ret", "\x87\xe1\xc3", 3},
	{0, 0, "xchg %esp,%edx ; ret", "xchg edx,esp ; ret", "\x87\xe2\xc3", 3},
	{0, 0, "xchg %esp,%edi ; ret", "xchg edi,esp ; ret", "\x87\xe7\xc3", 3},
	{0, 0, "xchg %esp,%esi ; ret", "xchg esi,esp ; ret", "\x87\xe6\xc3", 3},
	{0, 0, "xchg %esp,%ebp ; ret", "xchg ebp,esp ; ret", "\x87\xe5\xc3", 3},
	{0, 0, "xchg %esp,%esp ; ret", "xchg esp,esp ; ret", "\x87\xe4\xc3", 3},
	{0, 0, "mov %eax,%eax ; ret", "mov eax,eax ; ret", "\x89\xc0\xc3", 3},
	{0, 0, "mov %eax,%ebx ; ret", "mov ebx,eax ; ret", "\x89\xc3\xc3", 3},
	{0, 0, "mov %eax,%ecx ; ret", "mov ecx,eax ; ret", "\x89\xc1\xc3", 3},
	{0, 0, "mov %eax,%edx ; ret", "mov edx,eax ; ret", "\x89\xc2\xc3", 3},
	{0, 0, "mov %eax,%edi ; ret", "mov edi,eax ; ret", "\x89\xc7\xc3", 3},
	{0, 0, "mov %eax,%esi ; ret", "mov esi,eax ; ret", "\x89\xc6\xc3", 3},
	{0, 0, "mov %eax,%ebp ; ret", "mov ebp,eax ; ret", "\x89\xc5\xc3", 3},
	{0, 0, "mov %eax,%esp ; ret", "mov esp,eax ; ret", "\x89\xc4\xc3", 3},
	{0, 0, "mov %ebx,%eax ; ret", "mov eax,ebx ; ret", "\x89\xd8\xc3", 3},
	{0, 0, "mov %ebx,%ebx ; ret", "mov ebx,ebx ; ret", "\x89\xdb\xc3", 3},
	{0, 0, "mov %ebx,%ecx ; ret", "mov ecx,ebx ; ret", "\x89\xd9\xc3", 3},
	{0, 0, "mov %ebx,%edx ; ret", "mov edx,ebx ; ret", "\x89\xda\xc3", 3},
	{0, 0, "mov %ebx,%edi ; ret", "mov edi,ebx ; ret", "\x89\xdf\xc3", 3},
	{0, 0, "mov %ebx,%esi ; ret", "mov esi,ebx ; ret", "\x89\xde\xc3", 3},
	{0, 0, "mov %ebx,%ebp ; ret", "mov ebp,ebx ; ret", "\x89\xdd\xc3", 3},
	{0, 0, "mov %ebx,%esp ; ret", "mov esp,ebx ; ret", "\x89\xdc\xc3", 3},
	{0, 0, "mov %ecx,%eax ; ret", "mov eax,ecx ; ret", "\x89\xc8\xc3", 3},
	{0, 0, "mov %ecx,%ebx ; ret", "mov ebx,ecx ; ret", "\x89\xcb\xc3", 3},
	{0, 0, "mov %ecx,%ecx ; ret", "mov ecx,ecx ; ret", "\x89\xc9\xc3", 3},
	{0, 0, "mov %ecx,%edx ; ret", "mov edx,ecx ; ret", "\x89\xca\xc3", 3},
	{0, 0, "mov %ecx,%edi ; ret", "mov edi,ecx ; ret", "\x89\xcf\xc3", 3},
	{0, 0, "mov %ecx,%esi ; ret", "mov esi,ecx ; ret", "\x89\xce\xc3", 3},
	{0, 0, "mov %ecx,%ebp ; ret", "mov ebp,ecx ; ret", "\x89\xcd\xc3", 3},
	{0, 0, "mov %ecx,%esp ; ret", "mov esp,ecx ; ret", "\x89\xcc\xc3", 3},
	{0, 0, "mov %edx,%eax ; ret", "mov eax,edx ; ret", "\x89\xd0\xc3", 3},
	{0, 0, "mov %edx,%ebx ; ret", "mov ebx,edx ; ret", "\x89\xd3\xc3", 3},
	{0, 0, "mov %edx,%ecx ; ret", "mov ecx,edx ; ret", "\x89\xd1\xc3", 3},
	{0, 0, "mov %edx,%edx ; ret", "mov edx,edx ; ret", "\x89\xd2\xc3", 3},
	{0, 0, "mov %edx,%edi ; ret", "mov edi,edx ; ret", "\x89\xd7\xc3", 3},
	{0, 0, "mov %edx,%esi ; ret", "mov esi,edx ; ret", "\x89\xd6\xc3", 3},
	{0, 0, "mov %edx,%ebp ; ret", "mov ebp,edx ; ret", "\x89\xd5\xc3", 3},
	{0, 0, "mov %edx,%esp ; ret", "mov esp,edx ; ret", "\x89\xd4\xc3", 3},
	{0, 0, "mov %edi,%eax ; ret", "mov eax,edi ; ret", "\x89\xf8\xc3", 3},
	{0, 0, "mov %edi,%ebx ; ret", "mov ebx,edi ; ret", "\x89\xfb\xc3", 3},
	{0, 0, "mov %edi,%ecx ; ret", "mov ecx,edi ; ret", "\x89\xf9\xc3", 3},
	{0, 0, "mov %edi,%edx ; ret", "mov edx,edi ; ret", "\x89\xfa\xc3", 3},
	{0, 0, "mov %edi,%edi ; ret", "mov edi,edi ; ret", "\x89\xff\xc3", 3},
	{0, 0, "mov %edi,%esi ; ret", "mov esi,edi ; ret", "\x89\xfe\xc3", 3},
	{0, 0, "mov %edi,%ebp ; ret", "mov ebp,edi ; ret", "\x89\xfd\xc3", 3},
	{0, 0, "mov %edi,%esp ; ret", "mov esp,edi ; ret", "\x89\xfc\xc3", 3},
	{0, 0, "mov %esi,%eax ; ret", "mov eax,esi ; ret", "\x89\xf0\xc3", 3},
	{0, 0, "mov %esi,%ebx ; ret", "mov ebx,esi ; ret", "\x89\xf3\xc3", 3},
	{0, 0, "mov %esi,%ecx ; ret", "mov ecx,esi ; ret", "\x89\xf1\xc3", 3},
	{0, 0, "mov %esi,%edx ; ret", "mov edx,esi ; ret", "\x89\xf2\xc3", 3},
	{0, 0, "mov %esi,%edi ; ret", "mov edi,esi ; ret", "\x89\xf7\xc3", 3},
	{0, 0, "mov %esi,%esi ; ret", "mov esi,esi ; ret", "\x89\xf6\xc3", 3},
	{0, 0, "mov %esi,%ebp ; ret", "mov ebp,esi ; ret", "\x89\xf5\xc3", 3},
	{0, 0, "mov %esi,%esp ; ret", "mov esp,esi ; ret", "\x89\xf4\xc3", 3},
	{0, 0, "mov %ebp,%eax ; ret", "mov eax,ebp ; ret", "\x89\xe8\xc3", 3},
	{0, 0, "mov %ebp,%ebx ; ret", "mov ebx,ebp ; ret", "\x89\xeb\xc3", 3},
	{0, 0, "mov %ebp,%ecx ; ret", "mov ecx,ebp ; ret", "\x89\xe9\xc3", 3},
	{0, 0, "mov %ebp,%edx ; ret", "mov edx,ebp ; ret", "\x89\xea\xc3", 3},
	{0, 0, "mov %ebp,%edi ; ret", "mov edi,ebp ; ret", "\x89\xef\xc3", 3},
	{0, 0, "mov %ebp,%esi ; ret", "mov esi,ebp ; ret", "\x89\xee\xc3", 3},
	{0, 0, "mov %ebp,%ebp ; ret", "mov ebp,ebp ; ret", "\x89\xed\xc3", 3},
	{0, 0, "mov %ebp,%esp ; ret", "mov esp,ebp ; ret", "\x89\xec\xc3", 3},
	{0, 0, "mov %esp,%eax ; ret", "mov eax,esp ; ret", "\x89\xe0\xc3", 3},
	{0, 0, "mov %esp,%ebx ; ret", "mov ebx,esp ; ret", "\x89\xe3\xc3", 3},
	{0, 0, "mov %esp,%ecx ; ret", "mov ecx,esp ; ret", "\x89\xe1\xc3", 3},
	{0, 0, "mov %esp,%edx ; ret", "mov edx,esp ; ret", "\x89\xe2\xc3", 3},
	{0, 0, "mov %esp,%edi ; ret", "mov edi,esp ; ret", "\x89\xe7\xc3", 3},
	{0, 0, "mov %esp,%esi ; ret", "mov esi,esp ; ret", "\x89\xe6\xc3", 3},
	{0, 0, "mov %esp,%ebp ; ret", "mov ebp,esp ; ret", "\x89\xe5\xc3", 3},
	{0, 0, "mov %esp,%esp ; ret", "mov esp,esp ; ret", "\x89\xe4\xc3", 3},
	{0, 0, "mov (%eax),%eax ; ret", "mov eax,DWORD PTR [eax] ; ret", "\x8b\x00\xc3", 3},
	{0, 0, "mov (%eax),%ebx ; ret", "mov ebx,DWORD PTR [eax] ; ret", "\x8b\x18\xc3", 3},
	{0, 0, "mov (%eax),%ecx ; ret", "mov ecx,DWORD PTR [eax] ; ret", "\x8b\x08\xc3", 3},
	{0, 0, "mov (%eax),%edx ; ret", "mov edx,DWORD PTR [eax] ; ret", "\x8b\x10\xc3", 3},
	{0, 0, "mov (%eax),%edi ; ret", "mov edi,DWORD PTR [eax] ; ret", "\x8b\x38\xc3", 3},
	{0, 0, "mov (%eax),%esi ; ret", "mov esi,DWORD PTR [eax] ; ret", "\x8b\x30\xc3", 3},
	{0, 0, "mov (%eax),%ebp ; ret", "mov ebp,DWORD PTR [eax] ; ret", "\x8b\x28\xc3", 3},
	{0, 0, "mov (%eax),%esp ; ret", "mov esp,DWORD PTR [eax] ; ret", "\x8b\x20\xc3", 3},
	{0, 0, "mov (%ebx),%eax ; ret", "mov eax,DWORD PTR [ebx] ; ret", "\x8b\x03\xc3", 3},
	{0, 0, "mov (%ebx),%ebx ; ret", "mov ebx,DWORD PTR [ebx] ; ret", "\x8b\x1b\xc3", 3},
	{0, 0, "mov (%ebx),%ecx ; ret", "mov ecx,DWORD PTR [ebx] ; ret", "\x8b\x0b\xc3", 3},
	{0, 0, "mov (%ebx),%edx ; ret", "mov edx,DWORD PTR [ebx] ; ret", "\x8b\x13\xc3", 3},
	{0, 0, "mov (%ebx),%edi ; ret", "mov edi,DWORD PTR [ebx] ; ret", "\x8b\x3b\xc3", 3},
	{0, 0, "mov (%ebx),%esi ; ret", "mov esi,DWORD PTR [ebx] ; ret", "\x8b\x33\xc3", 3},
	{0, 0, "mov (%ebx),%ebp ; ret", "mov ebp,DWORD PTR [ebx] ; ret", "\x8b\x2b\xc3", 3},
	{0, 0, "mov (%ebx),%esp ; ret", "mov esp,DWORD PTR [ebx] ; ret", "\x8b\x23\xc3", 3},
	{0, 0, "mov (%ecx),%eax ; ret", "mov eax,DWORD PTR [ecx] ; ret", "\x8b\x01\xc3", 3},
	{0, 0, "mov (%ecx),%ebx ; ret", "mov ebx,DWORD PTR [ecx] ; ret", "\x8b\x19\xc3", 3},
	{0, 0, "mov (%ecx),%ecx ; ret", "mov ecx,DWORD PTR [ecx] ; ret", "\x8b\x09\xc3", 3},
	{0, 0, "mov (%ecx),%edx ; ret", "mov edx,DWORD PTR [ecx] ; ret", "\x8b\x11\xc3", 3},
	{0, 0, "mov (%ecx),%edi ; ret", "mov edi,DWORD PTR [ecx] ; ret", "\x8b\x39\xc3", 3},
	{0, 0, "mov (%ecx),%esi ; ret", "mov esi,DWORD PTR [ecx] ; ret", "\x8b\x31\xc3", 3},
	{0, 0, "mov (%ecx),%ebp ; ret", "mov ebp,DWORD PTR [ecx] ; ret", "\x8b\x29\xc3", 3},
	{0, 0, "mov (%ecx),%esp ; ret", "mov esp,DWORD PTR [ecx] ; ret", "\x8b\x21\xc3", 3},
	{0, 0, "mov (%edx),%eax ; ret", "mov eax,DWORD PTR [edx] ; ret", "\x8b\x02\xc3", 3},
	{0, 0, "mov (%edx),%ebx ; ret", "mov ebx,DWORD PTR [edx] ; ret", "\x8b\x1a\xc3", 3},
	{0, 0, "mov (%edx),%ecx ; ret", "mov ecx,DWORD PTR [edx] ; ret", "\x8b\x0a\xc3", 3},
	{0, 0, "mov (%edx),%edx ; ret", "mov edx,DWORD PTR [edx] ; ret", "\x8b\x12\xc3", 3},
	{0, 0, "mov (%edx),%edi ; ret", "mov edi,DWORD PTR [edx] ; ret", "\x8b\x3a\xc3", 3},
	{0, 0, "mov (%edx),%esi ; ret", "mov esi,DWORD PTR [edx] ; ret", "\x8b\x32\xc3", 3},
	{0, 0, "mov (%edx),%ebp ; ret", "mov ebp,DWORD PTR [edx] ; ret", "\x8b\x2a\xc3", 3},
	{0, 0, "mov (%edx),%esp ; ret", "mov esp,DWORD PTR [edx] ; ret", "\x8b\x22\xc3", 3},
	{0, 0, "mov (%edi),%eax ; ret", "mov eax,DWORD PTR [edi] ; ret", "\x8b\x07\xc3", 3},
	{0, 0, "mov (%edi),%ebx ; ret", "mov ebx,DWORD PTR [edi] ; ret", "\x8b\x1f\xc3", 3},
	{0, 0, "mov (%edi),%ecx ; ret", "mov ecx,DWORD PTR [edi] ; ret", "\x8b\x0f\xc3", 3},
	{0, 0, "mov (%edi),%edx ; ret", "mov edx,DWORD PTR [edi] ; ret", "\x8b\x17\xc3", 3},
	{0, 0, "mov (%edi),%edi ; ret", "mov edi,DWORD PTR [edi] ; ret", "\x8b\x3f\xc3", 3},
	{0, 0, "mov (%edi),%esi ; ret", "mov esi,DWORD PTR [edi] ; ret", "\x8b\x37\xc3", 3},
	{0, 0, "mov (%edi),%ebp ; ret", "mov ebp,DWORD PTR [edi] ; ret", "\x8b\x2f\xc3", 3},
	{0, 0, "mov (%edi),%esp ; ret", "mov esp,DWORD PTR [edi] ; ret", "\x8b\x27\xc3", 3},
	{0, 0, "mov (%esi),%eax ; ret", "mov eax,DWORD PTR [esi] ; ret", "\x8b\x06\xc3", 3},
	{0, 0, "mov (%esi),%ebx ; ret", "mov ebx,DWORD PTR [esi] ; ret", "\x8b\x1e\xc3", 3},
	{0, 0, "mov (%esi),%ecx ; ret", "mov ecx,DWORD PTR [esi] ; ret", "\x8b\x0e\xc3", 3},
	{0, 0, "mov (%esi),%edx ; ret", "mov edx,DWORD PTR [esi] ; ret", "\x8b\x16\xc3", 3},
	{0, 0, "mov (%esi),%edi ; ret", "mov edi,DWORD PTR [esi] ; ret", "\x8b\x3e\xc3", 3},
	{0, 0, "mov (%esi),%esi ; ret", "mov esi,DWORD PTR [esi] ; ret", "\x8b\x36\xc3", 3},
	{0, 0, "mov (%esi),%ebp ; ret", "mov ebp,DWORD PTR [esi] ; ret", "\x8b\x2e\xc3", 3},
	{0, 0, "mov (%esi),%esp ; ret", "mov esp,DWORD PTR [esi] ; ret", "\x8b\x26\xc3", 3},
	{0, 0, "mov 0x0(%ebp),%eax ; ret", "mov eax,DWORD PTR [ebp+0x0] ; ret", "\x8b\x45\x00\xc3", 4},
	{0, 0, "mov 0x0(%ebp),%ebx ; ret", "mov ebx,DWORD PTR [ebp+0x0] ; ret", "\x8b\x5d\x00\xc3", 4},
	{0, 0, "mov 0x0(%ebp),%ecx ; ret", "mov ecx,DWORD PTR [ebp+0x0] ; ret", "\x8b\x4d\x00\xc3", 4},
	{0, 0, "mov 0x0(%ebp),%edx ; ret", "mov edx,DWORD PTR [ebp+0x0] ; ret", "\x8b\x55\x00\xc3", 4},
	{0, 0, "mov 0x0(%ebp),%edi ; ret", "mov edi,DWORD PTR [ebp+0x0] ; ret", "\x8b\x7d\x00\xc3", 4},
	{0, 0, "mov 0x0(%ebp),%esi ; ret", "mov esi,DWORD PTR [ebp+0x0] ; ret", "\x8b\x75\x00\xc3", 4},
	{0, 0, "mov 0x0(%ebp),%ebp ; ret", "mov ebp,DWORD PTR [ebp+0x0] ; ret", "\x8b\x6d\x00\xc3", 4},
	{0, 0, "mov 0x0(%ebp),%esp ; ret", "mov esp,DWORD PTR [ebp+0x0] ; ret", "\x8b\x65\x00\xc3", 4},
	{0, 0, "mov (%esp),%eax ; ret", "mov eax,DWORD PTR [esp] ; ret", "\x8b\x04\x24\xc3", 4},
	{0, 0, "mov (%esp),%ebx ; ret", "mov ebx,DWORD PTR [esp] ; ret", "\x8b\x1c\x24\xc3", 4},
	{0, 0, "mov (%esp),%ecx ; ret", "mov ecx,DWORD PTR [esp] ; ret", "\x8b\x0c\x24\xc3", 4},
	{0, 0, "mov (%esp),%edx ; ret", "mov edx,DWORD PTR [esp] ; ret", "\x8b\x14\x24\xc3", 4},
	{0, 0, "mov (%esp),%edi ; ret", "mov edi,DWORD PTR [esp] ; ret", "\x8b\x3c\x24\xc3", 4},
	{0, 0, "mov (%esp),%esi ; ret", "mov esi,DWORD PTR [esp] ; ret", "\x8b\x34\x24\xc3", 4},
	{0, 0, "mov (%esp),%ebp ; ret", "mov ebp,DWORD PTR [esp] ; ret", "\x8b\x2c\x24\xc3", 4},
	{0, 0, "mov (%esp),%esp ; ret", "mov esp,DWORD PTR [esp] ; ret", "\x8b\x24\x24\xc3", 4},
	{0, 0, "mov %eax,(%eax) ; ret", "mov DWORD PTR [eax],eax ; ret", "\x89\x00\xc3", 3},
	{0, 0, "mov %eax,(%ebx) ; ret", "mov DWORD PTR [ebx],eax ; ret", "\x89\x03\xc3", 3},
	{0, 0, "mov %eax,(%ecx) ; ret", "mov DWORD PTR [ecx],eax ; ret", "\x89\x01\xc3", 3},
	{0, 0, "mov %eax,(%edx) ; ret", "mov DWORD PTR [edx],eax ; ret", "\x89\x02\xc3", 3},
	{0, 0, "mov %eax,(%edi) ; ret", "mov DWORD PTR [edi],eax ; ret", "\x89\x07\xc3", 3},
	{0, 0, "mov %eax,(%esi) ; ret", "mov DWORD PTR [esi],eax ; ret", "\x89\x06\xc3", 3},
	{0, 0, "mov %eax,0x0(%ebp) ; ret", "mov DWORD PTR [ebp+0x0],eax ; ret", "\x89\x45\x00\xc3", 4},
	{0, 0, "mov %eax,(%esp) ; ret", "mov DWORD PTR [esp],eax ; ret", "\x89\x04\x24\xc3", 4},
	{0, 0, "mov %ebx,(%eax) ; ret", "mov DWORD PTR [eax],ebx ; ret", "\x89\x18\xc3", 3},
	{0, 0, "mov %ebx,(%ebx) ; ret", "mov DWORD PTR [ebx],ebx ; ret", "\x89\x1b\xc3", 3},
	{0, 0, "mov %ebx,(%ecx) ; ret", "mov DWORD PTR [ecx],ebx ; ret", "\x89\x19\xc3", 3},
	{0, 0, "mov %ebx,(%edx) ; ret", "mov DWORD PTR [edx],ebx ; ret", "\x89\x1a\xc3", 3},
	{0, 0, "mov %ebx,(%edi) ; ret", "mov DWORD PTR [edi],ebx ; ret", "\x89\x1f\xc3", 3},
	{0, 0, "mov %ebx,(%esi) ; ret", "mov DWORD PTR [esi],ebx ; ret", "\x89\x1e\xc3", 3},
	{0, 0, "mov %ebx,0x0(%ebp) ; ret", "mov DWORD PTR [ebp+0x0],ebx ; ret", "\x89\x5d\x00\xc3", 4},
	{0, 0, "mov %ebx,(%esp) ; ret", "mov DWORD PTR [esp],ebx ; ret", "\x89\x1c\x24\xc3", 4},
	{0, 0, "mov %ecx,(%eax) ; ret", "mov DWORD PTR [eax],ecx ; ret", "\x89\x08\xc3", 3},
	{0, 0, "mov %ecx,(%ebx) ; ret", "mov DWORD PTR [ebx],ecx ; ret", "\x89\x0b\xc3", 3},
	{0, 0, "mov %ecx,(%ecx) ; ret", "mov DWORD PTR [ecx],ecx ; ret", "\x89\x09\xc3", 3},
	{0, 0, "mov %ecx,(%edx) ; ret", "mov DWORD PTR [edx],ecx ; ret", "\x89\x0a\xc3", 3},
	{0, 0, "mov %ecx,(%edi) ; ret", "mov DWORD PTR [edi],ecx ; ret", "\x89\x0f\xc3", 3},
	{0, 0, "mov %ecx,(%esi) ; ret", "mov DWORD PTR [esi],ecx ; ret", "\x89\x0e\xc3", 3},
	{0, 0, "mov %ecx,0x0(%ebp) ; ret", "mov DWORD PTR [ebp+0x0],ecx ; ret", "\x89\x4d\x00\xc3", 4},
	{0, 0, "mov %ecx,(%esp) ; ret", "mov DWORD PTR [esp],ecx ; ret", "\x89\x0c\x24\xc3", 4},
	{0, 0, "mov %edx,(%eax) ; ret", "mov DWORD PTR [eax],edx ; ret", "\x89\x10\xc3", 3},
	{0, 0, "mov %edx,(%ebx) ; ret", "mov DWORD PTR [ebx],edx ; ret", "\x89\x13\xc3", 3},
	{0, 0, "mov %edx,(%ecx) ; ret", "mov DWORD PTR [ecx],edx ; ret", "\x89\x11\xc3", 3},
	{0, 0, "mov %edx,(%edx) ; ret", "mov DWORD PTR [edx],edx ; ret", "\x89\x12\xc3", 3},
	{0, 0, "mov %edx,(%edi) ; ret", "mov DWORD PTR [edi],edx ; ret", "\x89\x17\xc3", 3},
	{0, 0, "mov %edx,(%esi) ; ret", "mov DWORD PTR [esi],edx ; ret", "\x89\x16\xc3", 3},
	{0, 0, "mov %edx,0x0(%ebp) ; ret", "mov DWORD PTR [ebp+0x0],edx ; ret", "\x89\x55\x00\xc3", 4},
	{0, 0, "mov %edx,(%esp) ; ret", "mov DWORD PTR [esp],edx ; ret", "\x89\x14\x24\xc3", 4},
	{0, 0, "mov %edi,(%eax) ; ret", "mov DWORD PTR [eax],edi ; ret", "\x89\x38\xc3", 3},
	{0, 0, "mov %edi,(%ebx) ; ret", "mov DWORD PTR [ebx],edi ; ret", "\x89\x3b\xc3", 3},
	{0, 0, "mov %edi,(%ecx) ; ret", "mov DWORD PTR [ecx],edi ; ret", "\x89\x39\xc3", 3},
	{0, 0, "mov %edi,(%edx) ; ret", "mov DWORD PTR [edx],edi ; ret", "\x89\x3a\xc3", 3},
	{0, 0, "mov %edi,(%edi) ; ret", "mov DWORD PTR [edi],edi ; ret", "\x89\x3f\xc3", 3},
	{0, 0, "mov %edi,(%esi) ; ret", "mov DWORD PTR [esi],edi ; ret", "\x89\x3e\xc3", 3},
	{0, 0, "mov %edi,0x0(%ebp) ; ret", "mov DWORD PTR [ebp+0x0],edi ; ret", "\x89\x7d\x00\xc3", 4},
	{0, 0, "mov %edi,(%esp) ; ret", "mov DWORD PTR [esp],edi ; ret", "\x89\x3c\x24\xc3", 4},
	{0, 0, "mov %esi,(%eax) ; ret", "mov DWORD PTR [eax],esi ; ret", "\x89\x30\xc3", 3},
	{0, 0, "mov %esi,(%ebx) ; ret", "mov DWORD PTR [ebx],esi ; ret", "\x89\x33\xc3", 3},
	{0, 0, "mov %esi,(%ecx) ; ret", "mov DWORD PTR [ecx],esi ; ret", "\x89\x31\xc3", 3},
	{0, 0, "mov %esi,(%edx) ; ret", "mov DWORD PTR [edx],esi ; ret", "\x89\x32\xc3", 3},
	{0, 0, "mov %esi,(%edi) ; ret", "mov DWORD PTR [edi],esi ; ret", "\x89\x37\xc3", 3},
	{0, 0, "mov %esi,(%esi) ; ret", "mov DWORD PTR [esi],esi ; ret", "\x89\x36\xc3", 3},
	{0, 0, "mov %esi,0x0(%ebp) ; ret", "mov DWORD PTR [ebp+0x0],esi ; ret", "\x89\x75\x00\xc3", 4},
	{0, 0, "mov %esi,(%esp) ; ret", "mov DWORD PTR [esp],esi ; ret", "\x89\x34\x24\xc3", 4},
	{0, 0, "mov %ebp,(%eax) ; ret", "mov DWORD PTR [eax],ebp ; ret", "\x89\x28\xc3", 3},
	{0, 0, "mov %ebp,(%ebx) ; ret", "mov DWORD PTR [ebx],ebp ; ret", "\x89\x2b\xc3", 3},
	{0, 0, "mov %ebp,(%ecx) ; ret", "mov DWORD PTR [ecx],ebp ; ret", "\x89\x29\xc3", 3},
	{0, 0, "mov %ebp,(%edx) ; ret", "mov DWORD PTR [edx],ebp ; ret", "\x89\x2a\xc3", 3},
	{0, 0, "mov %ebp,(%edi) ; ret", "mov DWORD PTR [edi],ebp ; ret", "\x89\x2f\xc3", 3},
	{0, 0, "mov %ebp,(%esi) ; ret", "mov DWORD PTR [esi],ebp ; ret", "\x89\x2e\xc3", 3},
	{0, 0, "mov %ebp,0x0(%ebp) ; ret", "mov DWORD PTR [ebp+0x0],ebp ; ret", "\x89\x6d\x00\xc3", 4},
	{0, 0, "mov %ebp,(%esp) ; ret", "mov DWORD PTR [esp],ebp ; ret", "\x89\x2c\x24\xc3", 4},
	{0, 0, "mov %esp,(%eax) ; ret", "mov DWORD PTR [eax],esp ; ret", "\x89\x20\xc3", 3},
	{0, 0, "mov %esp,(%ebx) ; ret", "mov DWORD PTR [ebx],esp ; ret", "\x89\x23\xc3", 3},
	{0, 0, "mov %esp,(%ecx) ; ret", "mov DWORD PTR [ecx],esp ; ret", "\x89\x21\xc3", 3},
	{0, 0, "mov %esp,(%edx) ; ret", "mov DWORD PTR [edx],esp ; ret", "\x89\x22\xc3", 3},
	{0, 0, "mov %esp,(%edi) ; ret", "mov DWORD PTR [edi],esp ; ret", "\x89\x27\xc3", 3},
	{0, 0, "mov %esp,(%esi) ; ret", "mov DWORD PTR [esi],esp ; ret", "\x89\x26\xc3", 3},
	{0, 0, "mov %esp,0x0(%ebp) ; ret", "mov DWORD PTR [ebp+0x0],esp ; ret", "\x89\x65\x00\xc3", 4},
	{0, 0, "mov %esp,(%esp) ; ret", "mov DWORD PTR [esp],esp ; ret", "\x89\x24\x24\xc3", 4},
	{0, 0, "syscall", "syscall", "\x0f\x05", 2},
	{0, 0, "int $0x80", "int 0x80", "\xcd\x80", 2},
	{0, 0, "sysenter", "sysenter", "\x0f\x34", 2},
	{0, 0, NULL, NULL, NULL, 0}
};
