---
title: "Quiz2"
author: "wfl9zy and gwu8ek"
date: "2023-09-22"
output: html_document
---

# Quiz 2: 

```{r}

library(dplyr)

grades<-data.frame(Student_ID=c("Student1","Student2", "Student3","Student4", "Student5"),
Quiz1=c(80,100,"-",95,100),
Quiz2=as.factor(c(90,100,95,90,82)),
Quiz3=c("-",100,90,100,100),
Midterm_Project=c(98,100,95,93,90),
Final_Project=c(95,92,95,100,90))

```

# Question 1:

```{r}



grades$Quiz1 = as.numeric(grades$Quiz1)

grades$Quiz1 <- replace(grades$Quiz1, is.na(grades$Quiz1), 0)

grades$Quiz3[grades$Student_ID == "Student1"] <- 85

grades$Quiz3 <- as.numeric(grades$Quiz3)

grades$Quiz2 = as.character(grades$Quiz2)

grades$Quiz2 <- as.numeric(grades$Quiz2)

grades2 <- grades

head(grades2)


```


# Question 2:

```{r}

grades3 <- grades2%>%
  mutate(Quiz_Average = (Quiz1 + Quiz2 + Quiz3)/3)


head(grades3)

```



# Question 3:

```{r}

grades4 <- grades3

grades4$Weighted_Average <- (grades4$Quiz_Average * 0.35) + (grades4$Midterm_Project * 0.3) + (grades$Final_Project*0.35)


head(grades4)

```


# Question 4


```{r}

grades5 <- grades4

grades5 = grades4%>%
  mutate(
    Grade = ifelse(Weighted_Average >= 95, "A",
              ifelse(Weighted_Average>=90, "A-",
                ifelse(Weighted_Average>=87,"B+",
                  ifelse(Weighted_Average>=83,"B",
                    ifelse(Weighted_Average>=80,"B-","F"))))))


head(grades5)

```