apiVersion: v1
kind: Service
metadata:
  name: bomb-service
spec:
  selector:
    app: bomb-pod  # Match the labels of your Pod
  ports:
    - protocol: TCP
      port: 3009  # The port your Node.js app is listening on
      targetPort: 3009
  type: NodePort